/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.tprog.estaciondetrabajo;

import com.tprog.logica.dt.DTLineaReserva;
import com.tprog.logica.dt.DTMinServicio;
import com.tprog.logica.dt.DTPromocion;
import com.tprog.logica.dt.DTProveedor;
import com.tprog.logica.dt.DTReserva;
import com.tprog.logica.dt.DTServicio;
import com.tprog.logica.interfaces.ICtrlProductos;
import com.tprog.logica.interfaces.ICtrlUsuarios;
import java.util.Date;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Iterator;
import java.util.Set;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class AltaDePromocion3 extends javax.swing.JInternalFrame {

	/**
	 * Creates new form ReservasCliente
	 *
	 * @param idCliente
	 * @param padre
	 */
	public AltaDePromocion3(AltaDePromocion2 padre, Set<DTMinServicio> servicios, ICtrlUsuarios ctrlUsuarios, ICtrlProductos ctrlProductos, String proveedor) {
		this.padre = padre;
        this.proveedor = proveedor;
		this.ctrlUsuarios = ctrlUsuarios;
        this.ctrlProductos = ctrlProductos;
        this.servicios = servicios;
        this.serviciosProm = new HashSet<DTMinServicio>();
        //this.servicios = ctrlProductos.listarServiciosProveedor();
		initComponents();
        setTitle("Alta de Promoción");
		//construyo lista para la interfaz usando el set
		if (servicios != null) {
			for (DTMinServicio dt : servicios) {
                listaServicios.add(dt.getIdServicio());
			}
		}
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        listaServiciosInterfaz = new javax.swing.JComboBox(listaServicios);
        panelUsuario = new javax.swing.JScrollPane();
        detalleServicio = new javax.swing.JTextArea();
        botonAtras = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        buttonAgregar = new javax.swing.JButton();
        buttonSiguiente = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setTitle("Servicios Proveedor");
        setPreferredSize(new java.awt.Dimension(640, 480));
        setVisible(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        listaServiciosInterfaz.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                listaServiciosInterfazInterfazComponentAdded(evt);
            }
        });
        listaServiciosInterfaz.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                listaServiciosInterfazItemStateChanged(evt);
            }
        });
        listaServiciosInterfaz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listaServiciosInterfazInterfazActionPerformed(evt);
            }
        });
        getContentPane().add(listaServiciosInterfaz, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 418, -1));

        detalleServicio.setEditable(false);
        detalleServicio.setColumns(20);
        detalleServicio.setLineWrap(true);
        detalleServicio.setRows(5);
        detalleServicio.setWrapStyleWord(true);
        panelUsuario.setViewportView(detalleServicio);

        getContentPane().add(panelUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, 269, 128));

        botonAtras.setText("< Atras");
        botonAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAtrasActionPerformed(evt);
            }
        });
        getContentPane().add(botonAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 400, -1, -1));

        jLabel1.setText("Agregue Servicios para crear la Promoción.");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, -1, -1));

        buttonAgregar.setText("Agregar");
        buttonAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAgregarActionPerformed(evt);
            }
        });
        getContentPane().add(buttonAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 300, -1, -1));

        buttonSiguiente.setText("Siguiente");
        buttonSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSiguienteActionPerformed(evt);
            }
        });
        getContentPane().add(buttonSiguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 400, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void listaServiciosInterfazInterfazComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_listaServiciosInterfazInterfazComponentAdded

    }//GEN-LAST:event_listaServiciosInterfazInterfazComponentAdded

    private void listaServiciosInterfazItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_listaServiciosInterfazItemStateChanged
		// TODO add your handling code here:
    }//GEN-LAST:event_listaServiciosInterfazItemStateChanged

    private void listaServiciosInterfazInterfazActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listaServiciosInterfazInterfazActionPerformed
	   String servicio = (String) listaServiciosInterfaz.getSelectedItem();
		if (servicio != null) {
			ctrlUsuarios.seleccionarServicio(servicio);
			DTServicio dt = ctrlUsuarios.infoServicio();
            
             DTMinServicio dtm = null;
            servicios = ctrlUsuarios.listarServiciosProveedor();
            Iterator it = servicios.iterator();
            boolean found = false;
            while (it.hasNext() && !found) {
                //System.out.println("323");
                DTMinServicio tmp = (DTMinServicio) it.next();
                if (tmp.getIdServicio().equals(servicio)) {
                    dtm = tmp; //es imposible que dt sea null al final del loop
                    //System.out.println("aaaasd");
                }

            }   
            ctrlProductos.seleccionarServicio(dtm);
			detalleServicio.setVisible(true);
			detalleServicio.setText(dt.toString());
		}       
    }//GEN-LAST:event_listaServiciosInterfazInterfazActionPerformed

    private void botonAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAtrasActionPerformed
		this.dispose();
		padre.setVisible(true);
    }//GEN-LAST:event_botonAtrasActionPerformed

    private void buttonAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAgregarActionPerformed
        // TODO add your handling code here:
        //agrego el servicio a la promo
        String servicio = (String) listaServiciosInterfaz.getSelectedItem();
        if (servicio != null) {
            //DTServicio dtS = ctrlUsuarios.infoServicio();
            //detalleServicio.setVisible(true);
            //detalleServicio.setText(dtS.toString());
            DTMinServicio dtmS = ctrlProductos.infoMinServicio();
            //String proveedorr = dtmS.getNicknameP();
            ctrlProductos.seleccionarProveedor(proveedor);
            ctrlProductos.seleccionarServicio(dtmS);
            // qe wea ermano
            ctrlProductos.seleccionarServicio(dtmS);
            //leer cantidad y fechas
            //validar cantidad
            ctrlProductos.agregarServicio(dtmS);
            serviciosProm.add(dtmS);
            JOptionPane.showMessageDialog(this, "Servicio agregado correctamente.", "Alta de Promoción", JOptionPane.INFORMATION_MESSAGE);
        }
        else{
            JOptionPane.showMessageDialog(this, "Seleccione un Servicio por favor.", "Error", JOptionPane.ERROR_MESSAGE);           
        }                        
    }//GEN-LAST:event_buttonAgregarActionPerformed

    private void buttonSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSiguienteActionPerformed
        // TODO add your handling code here:
        AltaDePromocion4 ap4 = new AltaDePromocion4(this, serviciosProm, ctrlUsuarios, ctrlProductos, proveedor);
        this.setVisible(false);
        getParent().add(ap4);
        ap4.setLocation(this.getLocation());
        ap4.setVisible(true);
    }//GEN-LAST:event_buttonSiguienteActionPerformed

	ICtrlUsuarios ctrlUsuarios;
    ICtrlProductos ctrlProductos;
	Set<DTMinServicio> servicios;
    Set<DTMinServicio> serviciosProm;
	AltaDePromocion2 padre;
    String proveedor;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAtras;
    private javax.swing.JButton buttonAgregar;
    private javax.swing.JButton buttonSiguiente;
    private javax.swing.JTextArea detalleServicio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JComboBox listaServiciosInterfaz;
    private Vector<String> listaServicios = new Vector<>();
    private javax.swing.JScrollPane panelUsuario;
    // End of variables declaration//GEN-END:variables
}
