/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.tprog.estaciondetrabajo;

import com.tprog.logica.dt.DTMinReserva;
import com.tprog.logica.interfaces.Fabrica;
import com.tprog.logica.interfaces.ICtrlProductos;
import java.util.Set;
import javax.swing.JOptionPane;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author marccio
 */
public class AltaCategoria extends javax.swing.JInternalFrame {

    /**
     * Creates new form ReservasCliente
     */
    public AltaCategoria() {
        initComponents();
    }
    
    void cargarDatos() {
        Fabrica f = Fabrica.getInstance();
        ctrlProductos = f.getICtrlProductos();
        //ctrlProductos.listarCategorias();
        //aca hay que construir el arbol y pum
        DefaultMutableTreeNode top = new DefaultMutableTreeNode("Categorias");
        //creo nodos
        DefaultMutableTreeNode b1 = new DefaultMutableTreeNode("Nodo1");
        DefaultMutableTreeNode b2 = new DefaultMutableTreeNode("Nodo2");
        DefaultMutableTreeNode b3 = new DefaultMutableTreeNode("Nodo3");
        DefaultMutableTreeNode b4 = new DefaultMutableTreeNode("Nodo4");
        DefaultMutableTreeNode b5 = new DefaultMutableTreeNode("Nodo5");
        DefaultMutableTreeNode b6 = new DefaultMutableTreeNode("Nodo6");
        //agrego nodos
        b5.add(b6);
        b4.add(b5);
        b3.add(b4);
        b1.add(b3);
        b1.add(b2);
        top.add(b1);
        arbolCategorias.setModel(new DefaultTreeModel(top));
        if (!casillaPadre.isSelected()) arbolCategorias.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonSalir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        casillaPadre = new javax.swing.JCheckBox();
        nombreCategoria = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        arbolCategorias = new javax.swing.JTree();
        jLabel2 = new javax.swing.JLabel();
        botonConfirmar = new javax.swing.JButton();

        setBorder(null);
        setPreferredSize(new java.awt.Dimension(690, 435));
        setVisible(true);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                formComponentHidden(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botonSalir.setText("Salir");
        botonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirActionPerformed(evt);
            }
        });
        getContentPane().add(botonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 290, -1, -1));

        jLabel1.setText("<html>Nombre de la nueva categoria</html>");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        casillaPadre.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        casillaPadre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                casillaPadreActionPerformed(evt);
            }
        });
        getContentPane().add(casillaPadre, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, -1, -1));

        nombreCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreCategoriaActionPerformed(evt);
            }
        });
        getContentPane().add(nombreCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, 110, -1));

        arbolCategorias.addTreeSelectionListener(new javax.swing.event.TreeSelectionListener() {
            public void valueChanged(javax.swing.event.TreeSelectionEvent evt) {
                arbolCategoriasValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(arbolCategorias);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 30, 200, 300));

        jLabel2.setText("<html>Tiene una categoría padre</html>");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, -1));

        botonConfirmar.setText("Confirmar creacion");
        botonConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonConfirmarActionPerformed(evt);
            }
        });
        getContentPane().add(botonConfirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_botonSalirActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        cargarDatos();
    }//GEN-LAST:event_formComponentShown

    private void formComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentHidden
        nombreCategoria.setText("");
        casillaPadre.setSelected(false);
    }//GEN-LAST:event_formComponentHidden

    private void nombreCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreCategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreCategoriaActionPerformed

    private void arbolCategoriasValueChanged(javax.swing.event.TreeSelectionEvent evt) {//GEN-FIRST:event_arbolCategoriasValueChanged
        DefaultMutableTreeNode nodo = (DefaultMutableTreeNode) arbolCategorias.getLastSelectedPathComponent();
        if (nodo != null) {
            System.out.println("Seleccionaste " + nodo.toString());
        }
    }//GEN-LAST:event_arbolCategoriasValueChanged

    private void casillaPadreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_casillaPadreActionPerformed
        if (!casillaPadre.isSelected()) arbolCategorias.setEnabled(false);
        else arbolCategorias.setEnabled(true);
    }//GEN-LAST:event_casillaPadreActionPerformed

    private void botonConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonConfirmarActionPerformed
        if (!nombreCategoria.getText().equals("")) { //nombre no vacío
            if (casillaPadre.isSelected()) {
                
            } else {
                String idCategoria =  ((DefaultMutableTreeNode) arbolCategorias.getLastSelectedPathComponent()).toString();
                if (! ctrlProductos.seleccionarCategoriaPadre(idCategoria))
                    JOptionPane.showMessageDialog(this, "Esa categoria tiene servicios asociados; escoja otra", "Categoria padre erronea", JOptionPane.INFORMATION_MESSAGE);
                else
                    if (!ctrlProductos.idCategoriaDisponible(idCategoria))
                        JOptionPane.showMessageDialog(this, "El nombre escogido esta en uso; escoja otro", "Nombre invalido", JOptionPane.INFORMATION_MESSAGE);
                    else {
                        ctrlProductos.altaCategoria();
                        JOptionPane.showMessageDialog(this, "La categoria fue creada con exito", "Exito", JOptionPane.INFORMATION_MESSAGE);
                        cargarDatos();
                    }
            }
        } else JOptionPane.showMessageDialog(this, "Por favor ingrese un nombre para la categoria", "Campo vacio", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_botonConfirmarActionPerformed

    ICtrlProductos ctrlProductos;
    Set<DTMinReserva> reservas;
    VerInformacionDeCliente padre;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTree arbolCategorias;
    private javax.swing.JButton botonConfirmar;
    private javax.swing.JButton botonSalir;
    private javax.swing.JCheckBox casillaPadre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nombreCategoria;
    // End of variables declaration//GEN-END:variables
}
