/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.tprog.estaciondetrabajo;

import com.tprog.logica.dt.DTUbicacion;
import com.tprog.logica.interfaces.ICtrlProductos;
import java.awt.event.MouseListener;
import java.io.File;
import static java.lang.Integer.parseInt;
import static java.lang.Integer.parseInt;
import static java.lang.Integer.parseInt;
import java.util.Set;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author ignacio.prandi
 */
public class AltaDeServicio5 extends javax.swing.JInternalFrame {
    private ICtrlProductos ctrlProductos;
    private AltaDeServicio4 padre;

    /**
     * Creates new form AltaDeServicio5
     * @param padre
     * @param ctrlProductos
     */
    public AltaDeServicio5(AltaDeServicio4 padre, ICtrlProductos ctrlProductos) {
        initComponents();
        setTitle("Alta de Servicio");
        this.padre = padre;
        this.ctrlProductos = ctrlProductos;
        BasicInternalFrameUI basicInternalFrameUI = ((javax.swing.plaf.basic.BasicInternalFrameUI) this.getUI());
        for (MouseListener listener : basicInternalFrameUI.getNorthPane().getMouseListeners()) {
            basicInternalFrameUI.getNorthPane().removeMouseListener(listener);
        }        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        listaCiudadesOrigen = new javax.swing.JComboBox();
        listaCiudadesDestino = new javax.swing.JComboBox();
        buttonConfirmar = new javax.swing.JButton();
        buttonAtras = new javax.swing.JButton();
        buttonSalir = new javax.swing.JButton();
        checkBoxCiudadDestino = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textPaneDescripcion = new javax.swing.JTextPane();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        textPanePrecio = new javax.swing.JTextPane();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        buttonImagen2 = new javax.swing.JButton();
        buttonImagen3 = new javax.swing.JButton();
        labelImagen1 = new javax.swing.JLabel();
        labelImagen2 = new javax.swing.JLabel();
        labelImagen3 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(640, 480));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Ingrese los datos del servicio y haga click en \"Confirmar\".");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 11, 480, -1));

        jLabel2.setText("Ciudad de Origen");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 204, 147, -1));

        listaCiudadesOrigen.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(listaCiudadesOrigen, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, 166, -1));

        listaCiudadesDestino.setVisible(false);
        listaCiudadesDestino.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        listaCiudadesDestino.setFocusable(false);
        getContentPane().add(listaCiudadesDestino, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, 168, -1));

        buttonConfirmar.setText("Confirmar");
        buttonConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonConfirmarActionPerformed(evt);
            }
        });
        getContentPane().add(buttonConfirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 400, -1, -1));

        buttonAtras.setText("Atras");
        buttonAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAtrasActionPerformed(evt);
            }
        });
        getContentPane().add(buttonAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 400, -1, -1));

        buttonSalir.setText("Salir");
        buttonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSalirActionPerformed(evt);
            }
        });
        getContentPane().add(buttonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 410, -1, -1));

        checkBoxCiudadDestino.setSelected(false);
        checkBoxCiudadDestino.setText("Ciudad de Destino");
        checkBoxCiudadDestino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxCiudadDestinoActionPerformed(evt);
            }
        });
        getContentPane().add(checkBoxCiudadDestino, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, -1, -1));

        jLabel3.setText("Descripción");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 43, -1, -1));

        jScrollPane1.setViewportView(textPaneDescripcion);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 75, 169, -1));

        jLabel4.setText("Precio");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 104, -1, -1));

        jScrollPane2.setViewportView(textPanePrecio);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 164, 168, -1));

        jLabel5.setText("Imágenes");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(305, 43, -1, -1));

        jButton1.setText("Imágen 1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 90, -1, -1));

        buttonImagen2.setText("Imágen 2");
        buttonImagen2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonImagen2ActionPerformed(evt);
            }
        });
        getContentPane().add(buttonImagen2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 200, -1, -1));

        buttonImagen3.setText("Imágen 3");
        buttonImagen3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonImagen3ActionPerformed(evt);
            }
        });
        getContentPane().add(buttonImagen3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 300, -1, -1));

        labelImagen1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(labelImagen1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 70, 120, 80));

        labelImagen2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(labelImagen2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 180, 120, 80));

        labelImagen3.setAutoscrolls(true);
        labelImagen3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(labelImagen3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 280, 120, 80));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonConfirmarActionPerformed
        // TODO add your handling code here:
        String descripcion = textPaneDescripcion.getText();
        String precioString = textPanePrecio.getText();
        boolean okDescripcion = !(descripcion.isEmpty());
        boolean okPrecio = (precioString.matches("([0-9]|)+"))&&(precioString.length() >= 1);
        int precio = 0;
        if (okPrecio)  precio = parseInt(precioString);
        Set<String> imagenes = null;
        imagenes.add(ruta1);
        imagenes.add(ruta2);
        imagenes.add(ruta2);
        boolean okImagenes = true;
        String ciudadOrigen = null;
        ciudadOrigen = (String) listaCiudadesOrigen.getSelectedItem();
        String paisOrigen = null; // falta
        DTUbicacion origen = new DTUbicacion(ciudadOrigen, paisOrigen);
        ctrlProductos.seleccionarOrigen(origen);
        if (checkBoxCiudadDestino.isSelected()){
            String ciudadDestino = null;
            ciudadDestino = (String) listaCiudadesDestino.getSelectedItem();
            String paisDestino = null; // falta
            DTUbicacion destino = new DTUbicacion(ciudadDestino, paisDestino);
            ctrlProductos.seleccionarDestino(destino);
        }
        if ((okDescripcion)&&(okPrecio)&&(okImagenes))
            ctrlProductos.altaServicio(descripcion, precio, imagenes);
        else {
            String error = "";
            if (!okDescripcion) error = "Por favor ingrese una descripción.";
            else if(!okPrecio) error = "Por favor verifique el precio.";
            JOptionPane.showMessageDialog(this, "Error! "+error, "Alta de Servicio", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_buttonConfirmarActionPerformed

    private void checkBoxCiudadDestinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxCiudadDestinoActionPerformed
        // TODO add your handling code here:
        if (checkBoxCiudadDestino.isSelected()) listaCiudadesDestino.setVisible(true);
        else listaCiudadesDestino.setVisible(false);
    }//GEN-LAST:event_checkBoxCiudadDestinoActionPerformed

    private void buttonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSalirActionPerformed
        // TODO add your handling code here:
         this.dispose();
    }//GEN-LAST:event_buttonSalirActionPerformed

    private void buttonAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAtrasActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        this.padre.setVisible(true);
    }//GEN-LAST:event_buttonAtrasActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JFileChooser fc = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter(
  	            "Imágenes JPG & PNG ", "jpg", "png");
        fc.setFileFilter(filter);       
  	            int seleccion = fc.showDialog(this, "Adjuntar");
                    if (seleccion == JFileChooser.APPROVE_OPTION) {
  	                // Para guardar la imagen.*******************************************
  	                File file = fc.getSelectedFile();
                        ruta1 = file.getPath();
                        try {
                            labelImagen1.setIcon(new ImageIcon(ruta1));
                            labelImagen1.setHorizontalAlignment(JLabel.CENTER);
                            labelImagen1.setVerticalAlignment(JLabel.CENTER);
                         } catch (Exception e) {
                            System.out.println(e.getMessage());
                         }
                    }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void buttonImagen2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonImagen2ActionPerformed
        // TODO add your handling code here:
        JFileChooser fc = new JFileChooser();
        String rutname = "";
        FileNameExtensionFilter filter = new FileNameExtensionFilter(
  	            "Imágenes JPG & PNG ", "jpg", "png");
        fc.setFileFilter(filter);       
  	            int seleccion = fc.showDialog(this, "Adjuntar");
                    if (seleccion == JFileChooser.APPROVE_OPTION) {
  	                // Para guardar la imagen.*******************************************
  	                File file = fc.getSelectedFile();
                        ruta2 = file.getPath();
                        try {
                            labelImagen2.setIcon(new ImageIcon(ruta2));
                            labelImagen2.setHorizontalAlignment(JLabel.CENTER);
                            labelImagen2.setVerticalAlignment(JLabel.CENTER);
                         } catch (Exception e) {
                            System.out.println(e.getMessage());
                         }
                    }
    }//GEN-LAST:event_buttonImagen2ActionPerformed

    private void buttonImagen3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonImagen3ActionPerformed
        // TODO add your handling code here:
        JFileChooser fc = new JFileChooser();
        String rutname = "";
        FileNameExtensionFilter filter = new FileNameExtensionFilter(
  	            "Imágenes JPG & PNG ", "jpg", "png");
        fc.setFileFilter(filter);       
  	            int seleccion = fc.showDialog(this, "Adjuntar");
                    if (seleccion == JFileChooser.APPROVE_OPTION) {
  	                // Para guardar la imagen.*******************************************
  	                File file = fc.getSelectedFile();
                        ruta3 = file.getPath();
                        try {
                            labelImagen3.setIcon(new ImageIcon(ruta3));
                            labelImagen3.setHorizontalAlignment(JLabel.CENTER);
                            labelImagen3.setVerticalAlignment(JLabel.CENTER);
                         } catch (Exception e) {
                            System.out.println(e.getMessage());
                         }
                    }
    }//GEN-LAST:event_buttonImagen3ActionPerformed
    
    String ruta1;
    String ruta2;
    String ruta3;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAtras;
    private javax.swing.JButton buttonConfirmar;
    private javax.swing.JButton buttonImagen2;
    private javax.swing.JButton buttonImagen3;
    private javax.swing.JButton buttonSalir;
    private javax.swing.JCheckBox checkBoxCiudadDestino;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelImagen1;
    private javax.swing.JLabel labelImagen2;
    private javax.swing.JLabel labelImagen3;
    private javax.swing.JComboBox listaCiudadesDestino;
    private javax.swing.JComboBox listaCiudadesOrigen;
    private javax.swing.JTextPane textPaneDescripcion;
    private javax.swing.JTextPane textPanePrecio;
    // End of variables declaration//GEN-END:variables
}
