/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.tprog.estaciondetrabajo;

import com.tprog.logica.controladores.CtrlUsuarios;
import com.tprog.logica.dt.DTUsuario;
import com.tprog.logica.interfaces.Fabrica;
import static com.tprog.logica.interfaces.Fabrica.getInstance;
import com.tprog.logica.interfaces.ICtrlUsuarios;
import java.awt.BorderLayout;
import java.io.File;
import static java.lang.Integer.parseInt;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author User
 */
public class AltaDeUsuario2 extends javax.swing.JInternalFrame {
    private final AltaDeUsuario1 padre;
    private String ruta;
    private final ICtrlUsuarios ictrlU;

    /**
     * Creates new form AltaDeUsuario2
     * @param padre
     */
    public AltaDeUsuario2(AltaDeUsuario1 padre, String nickname, String email, ICtrlUsuarios ictrlU) {
        
        setTitle("Alta de Usuario");
        //ctrlU = new CtrlUsuarios();
        //fabrica = Fabrica.getInstance();
        this.padre = padre;
        this.nickname = nickname;
        this.email = email;
        
        initComponents();
        this.ictrlU = ictrlU;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoBotones = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textPaneNombre = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        textPaneApellido = new javax.swing.JTextPane();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        buttonSeleccionar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        textPaneDia = new javax.swing.JTextPane();
        comboBoxMeses = new javax.swing.JComboBox();
        jScrollPane4 = new javax.swing.JScrollPane();
        textPaneAnio = new javax.swing.JTextPane();
        jLabel10 = new javax.swing.JLabel();
        radioButtonCliente = new javax.swing.JRadioButton();
        radioButtonProveedor = new javax.swing.JRadioButton();
        labelNombreEmpresa = new javax.swing.JLabel();
        scrollPaneNombreEmpresa = new javax.swing.JScrollPane();
        textPaneNombreEmpresa = new javax.swing.JTextPane();
        labelLinkEmpresa = new javax.swing.JLabel();
        scrollPaneLinkEmpresa = new javax.swing.JScrollPane();
        textPaneLinkEmpresa = new javax.swing.JTextPane();
        buttonAtras = new javax.swing.JButton();
        buttonConfirmar = new javax.swing.JButton();
        buttonSalir = new javax.swing.JButton();

        grupoBotones.add(radioButtonCliente);
        grupoBotones.add(radioButtonProveedor);

        jLabel1.setText("Complete los datos del nuevo Usuario y haga click  en  \"Confirmar\".");

        jLabel2.setText("Nombre");

        jLabel3.setText("Apellido");

        jScrollPane1.setViewportView(textPaneNombre);

        jScrollPane2.setViewportView(textPaneApellido);

        jLabel4.setText("Imágen");

        jLabel5.setText("LA IMAGEN");

        buttonSeleccionar.setText("Seleccionar");
        buttonSeleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSeleccionarActionPerformed(evt);
            }
        });

        jLabel6.setText("Fecha de Nacimiento");

        jLabel7.setText("Día");

        jLabel8.setText("Mes");

        jLabel9.setText("Año");

        jScrollPane3.setViewportView(textPaneDia);

        comboBoxMeses.setModel(new javax.swing.DefaultComboBoxModel(meses));

        jScrollPane4.setViewportView(textPaneAnio);

        jLabel10.setText("Tipo de Usuario");

        radioButtonCliente.setText("Cliente");
        radioButtonCliente.setSelected(true);
        radioButtonCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioButtonClienteActionPerformed(evt);
            }
        });

        radioButtonProveedor.setText("Proveedor");
        radioButtonCliente.setSelected(false);
        radioButtonProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioButtonProveedorActionPerformed(evt);
            }
        });

        labelNombreEmpresa.setVisible(false);
        labelNombreEmpresa.setText("Nombre de la Empresa ");

        scrollPaneNombreEmpresa.setVisible(false);

        textPaneNombreEmpresa.setVisible(false);
        scrollPaneNombreEmpresa.setViewportView(textPaneNombreEmpresa);

        labelLinkEmpresa.setVisible(false);
        labelLinkEmpresa.setText("Link de la Empresa");

        scrollPaneLinkEmpresa.setVisible(false);

        textPaneLinkEmpresa.setVisible(false);
        scrollPaneLinkEmpresa.setViewportView(textPaneLinkEmpresa);

        buttonAtras.setText("Atras");
        buttonAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAtrasActionPerformed(evt);
            }
        });

        buttonConfirmar.setText("Confirmar");
        buttonConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonConfirmarActionPerformed(evt);
            }
        });

        buttonSalir.setText("Salir");
        buttonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(125, 125, 125)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(10, 10, 10)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addComponent(jLabel4)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(48, 48, 48)
                                                .addComponent(buttonSeleccionar)))
                                        .addGap(88, 88, 88)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel7)
                                                .addGap(18, 18, 18)
                                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel8)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(comboBoxMeses, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel9)
                                                .addGap(18, 18, 18)
                                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(labelLinkEmpresa)
                                                    .addComponent(labelNombreEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(scrollPaneNombreEmpresa, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                                                    .addComponent(scrollPaneLinkEmpresa)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(buttonAtras)
                                                .addGap(26, 26, 26)
                                                .addComponent(buttonConfirmar))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(174, 174, 174)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(radioButtonCliente)
                                                .addGap(18, 18, 18)
                                                .addComponent(radioButtonProveedor))))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(73, 73, 73)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 16, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(buttonSalir)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(jLabel8)
                        .addComponent(jLabel9)
                        .addComponent(comboBoxMeses, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(11, 11, 11)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel10)
                                .addComponent(radioButtonCliente)
                                .addComponent(radioButtonProveedor)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonSeleccionar))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(scrollPaneNombreEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelNombreEmpresa))))
                        .addGap(21, 21, 21)
                        .addComponent(labelLinkEmpresa))
                    .addComponent(scrollPaneLinkEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonAtras)
                    .addComponent(buttonConfirmar))
                .addGap(5, 5, 5)
                .addComponent(buttonSalir)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonSeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSeleccionarActionPerformed
        // TODO add your handling code here:
        JFileChooser fc = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter(
  	            "Imágenes JPG & PNG ", "jpg", "png");
        fc.setFileFilter(filter);       
  	            int seleccion = fc.showDialog(this, "Adjuntar");
                    if (seleccion == JFileChooser.APPROVE_OPTION) {
  	                // Para guardar la imagen.*******************************************
  	                File file = fc.getSelectedFile();
                        ruta = file.getPath();
                    }
    }//GEN-LAST:event_buttonSeleccionarActionPerformed

    private void radioButtonClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioButtonClienteActionPerformed
        // TODO add your handling code here:
        scrollPaneNombreEmpresa.setVisible(false);
        scrollPaneLinkEmpresa.setVisible(false);
        labelNombreEmpresa.setVisible(false);
        labelLinkEmpresa.setVisible(false);
        textPaneNombreEmpresa.setVisible(false);
        textPaneLinkEmpresa.setVisible(false);
    }//GEN-LAST:event_radioButtonClienteActionPerformed

    private void radioButtonProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioButtonProveedorActionPerformed
        // TODO add your handling code here:
        scrollPaneNombreEmpresa.setVisible(true);
        scrollPaneLinkEmpresa.setVisible(true);
        labelNombreEmpresa.setVisible(true);
        labelLinkEmpresa.setVisible(true);
        textPaneNombreEmpresa.setVisible(true);
        textPaneLinkEmpresa.setVisible(true);
    }//GEN-LAST:event_radioButtonProveedorActionPerformed

    private void buttonConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonConfirmarActionPerformed
        // TODO add your handling code here:
        String nombre = textPaneNombre.getText();
        String apellido = textPaneApellido.getText();
        String imagen = null;
        String diaString = textPaneDia.getText();
        int dia = parseInt(diaString);
        //String mes = comboBoxMeses.getSelectedItem().toString();
        int mes = comboBoxMeses.getSelectedIndex() + 1;
        String anioString = textPaneAnio.getText();
        int anio = parseInt(anioString);
        boolean okNombre = (nombre.matches("([a-z]|[A-Z]|)+"))&&(nombre.length() >= 1);
        boolean okApellido = (nombre.matches("([a-z]|[A-Z]|)+"))&&(apellido.length() >= 1);
        boolean okDia = (diaString.matches("([0-9]|)+"))&&(diaString.length() >= 1);
        boolean okAnio = (anioString.matches("([0-9]|)+"))&&(anioString.length() >= 1);
        boolean proveedor = radioButtonProveedor.isSelected();
        boolean ok = (okNombre && okApellido && okDia && okAnio);
        Date fechaNacimiento = new Date();
        fechaNacimiento.setDate(dia);
        fechaNacimiento.setMonth(mes);
        fechaNacimiento.setYear(anio);
        if (ok){
            DTUsuario dtU = new DTUsuario(nickname, nombre, apellido, email, imagen, fechaNacimiento);
            //ICtrlUsuarios ictrlU = fabrica.getICtrlUsuarios();
            ictrlU.ingresarDatosUsuario(dtU, proveedor);
            if (proveedor){
                System.out.println("proveee");
                String nombreEmpresa = textPaneNombreEmpresa.getText();
                String linkEmpresa = textPaneLinkEmpresa.getText();
                boolean okNombreEmpresa = (nombreEmpresa.matches("([a-z]|[A-Z]|)+"))&&(nombreEmpresa.length() >= 1);
                boolean okLinkEmpresa = (linkEmpresa.matches("([a-z]|[A-Z]|)+"))&&(linkEmpresa.length() >= 1);
                boolean okP = (okNombreEmpresa && okLinkEmpresa);
                if (okP) ictrlU.ingresarDatosProveedor(nombreEmpresa, linkEmpresa); 
            }
            ictrlU.altaUsuario();
            JOptionPane.showMessageDialog(this, "Usuario creado con éxito", "Alta de Usuario", JOptionPane.INFORMATION_MESSAGE);
            this.dispose();
        }
        else {
            JOptionPane.showMessageDialog(this, "Verifique sus datos", "Alta de Usuario", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_buttonConfirmarActionPerformed

    private void buttonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSalirActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_buttonSalirActionPerformed

    private void buttonAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAtrasActionPerformed
            this.setVisible(false);
            padre.setVisible(true);
    }//GEN-LAST:event_buttonAtrasActionPerformed
    
    String nickname;
    String email;
    //Fabrica fabrica;
    //CtrlUsuarios ctrlU ;
    private String[] meses = {"Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Setiembre",
        "Octubre", "Noviembre", "Diciembre"};
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAtras;
    private javax.swing.JButton buttonConfirmar;
    private javax.swing.JButton buttonSalir;
    private javax.swing.JButton buttonSeleccionar;
    private javax.swing.JComboBox comboBoxMeses;
    private javax.swing.ButtonGroup grupoBotones;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel labelLinkEmpresa;
    private javax.swing.JLabel labelNombreEmpresa;
    private javax.swing.JRadioButton radioButtonCliente;
    private javax.swing.JRadioButton radioButtonProveedor;
    private javax.swing.JScrollPane scrollPaneLinkEmpresa;
    private javax.swing.JScrollPane scrollPaneNombreEmpresa;
    private javax.swing.JTextPane textPaneAnio;
    private javax.swing.JTextPane textPaneApellido;
    private javax.swing.JTextPane textPaneDia;
    private javax.swing.JTextPane textPaneLinkEmpresa;
    private javax.swing.JTextPane textPaneNombre;
    private javax.swing.JTextPane textPaneNombreEmpresa;
    // End of variables declaration//GEN-END:variables
}

