/*
* To change this license header, choose License Headers in Project Properties.
* To change this template file, choose Tools | Templates
* and open the template in the editor.
*/
package com.tprog.estaciondetrabajo;

import com.tprog.logica.dt.DTServicio;
import com.tprog.logica.dt.DTUbicacion;
import com.tprog.logica.interfaces.ICtrlProductos;
import java.awt.event.MouseListener;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.tree.DefaultMutableTreeNode;

/**
 *
 * @author marccio
 */
public class ModificacionUbicacion extends javax.swing.JInternalFrame {
    
    /**
     * Creates new form ReservasCliente
     * @param idCliente
     * @param padre
     */
    public ModificacionUbicacion(ModificacionServicio padre, DefaultMutableTreeNode arbolCiudades, ICtrlProductos ctrlProductos) {
        this.padre = padre;
        this.ctrlProductos = ctrlProductos;
        this.arbolCiudades = arbolCiudades;
        initComponents();
        BasicInternalFrameUI basicInternalFrameUI = ((javax.swing.plaf.basic.BasicInternalFrameUI) this.getUI());
        for (MouseListener listener : basicInternalFrameUI.getNorthPane().getMouseListeners()) {
            basicInternalFrameUI.getNorthPane().removeMouseListener(listener);
        }
        actualizarInterfaz();
    }
    
    private void actualizarInterfaz() {
        DTServicio dt = ctrlProductos.infoServicio();
        labelOrigen.setText("<html>" + dt.getOrigen().getCiudad() + ", " + dt.getOrigen().getPais() + "</html>");
        labelDestino.setText("<html>" + dt.getDestino().getCiudad() + ", " + dt.getDestino().getPais() + "</html>");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonSalir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        arbolCiudadesOrigenInterfaz = new javax.swing.JTree(arbolCiudades);
        jScrollPane2 = new javax.swing.JScrollPane();
        arbolCiudadesDestinoInterfaz = new javax.swing.JTree(arbolCiudades);
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        botonConfirmar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        labelOrigen = new javax.swing.JLabel();
        labelDestino = new javax.swing.JLabel();

        setBorder(null);
        setPreferredSize(new java.awt.Dimension(690, 435));
        setVisible(true);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botonSalir.setText("Salir");
        botonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirActionPerformed(evt);
            }
        });
        getContentPane().add(botonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 350, -1, -1));

        arbolCiudadesOrigenInterfaz.addTreeSelectionListener(new javax.swing.event.TreeSelectionListener() {
            public void valueChanged(javax.swing.event.TreeSelectionEvent evt) {
                arbolCiudadesOrigenInterfazValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(arbolCiudadesOrigenInterfaz);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 200, 150));

        arbolCiudadesDestinoInterfaz.addTreeSelectionListener(new javax.swing.event.TreeSelectionListener() {
            public void valueChanged(javax.swing.event.TreeSelectionEvent evt) {
                arbolCiudadesDestinoInterfazValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(arbolCiudadesDestinoInterfaz);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 50, 200, 150));

        jLabel1.setText("Seleccione un nuevo origen");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, -1, -1));

        jLabel2.setText("Seleccione un nuevo destino");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 20, -1, -1));

        jLabel3.setText("<html>Las ciudades seleccionadas son las ubicaciones actuales del servicio</html>");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 300, -1, -1));

        botonConfirmar.setText("Confirmar cambios");
        botonConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonConfirmarActionPerformed(evt);
            }
        });
        getContentPane().add(botonConfirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 350, -1, -1));

        jLabel4.setText("Origen actual:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, -1, -1));

        jLabel5.setText("Destino actual:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 240, -1, -1));

        labelOrigen.setText("jLabel6");
        getContentPane().add(labelOrigen, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, 150, 60));

        labelDestino.setText("jLabel7");
        getContentPane().add(labelDestino, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 220, 150, 60));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void botonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirActionPerformed
        arbolCiudades.removeAllChildren();
        this.dispose();
        padre.setVisible(true);
    }//GEN-LAST:event_botonSalirActionPerformed
    
    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        /*
        descripcionInterfaz.setText(servicio.getDescripcion());
        precioInterfaz.setText(Float.toString(servicio.getPrecio()));
        */        
    }//GEN-LAST:event_formComponentShown
    
    private void arbolCiudadesOrigenInterfazValueChanged(javax.swing.event.TreeSelectionEvent evt) {//GEN-FIRST:event_arbolCiudadesOrigenInterfazValueChanged
        DefaultMutableTreeNode nodo = (DefaultMutableTreeNode) arbolCiudadesOrigenInterfaz.getLastSelectedPathComponent();
        if (nodo != null) {
            System.out.println("Seleccionaste " + nodo.toString());
        }
    }//GEN-LAST:event_arbolCiudadesOrigenInterfazValueChanged
    
    private void arbolCiudadesDestinoInterfazValueChanged(javax.swing.event.TreeSelectionEvent evt) {//GEN-FIRST:event_arbolCiudadesDestinoInterfazValueChanged
        DefaultMutableTreeNode nodo = (DefaultMutableTreeNode) arbolCiudadesOrigenInterfaz.getLastSelectedPathComponent();
        if (nodo != null) {
            System.out.println("Seleccionaste " + nodo.toString());
        }
    }//GEN-LAST:event_arbolCiudadesDestinoInterfazValueChanged
    
    private void botonConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonConfirmarActionPerformed
        //construir DTUbicacion's en base a la hoja seleccionada y al padre
        //origen
        DefaultMutableTreeNode nodoOrigen = (DefaultMutableTreeNode) arbolCiudadesOrigenInterfaz.getLastSelectedPathComponent();
        DefaultMutableTreeNode nodoDestino = (DefaultMutableTreeNode) arbolCiudadesDestinoInterfaz.getLastSelectedPathComponent();
        if (nodoOrigen != null && nodoDestino != null && nodoOrigen.isLeaf() && nodoDestino.isLeaf()) {
            DTUbicacion dtOrigen = new DTUbicacion(nodoOrigen.toString(), nodoOrigen.getParent().toString());
            DTUbicacion dtDestino = new DTUbicacion(nodoDestino.toString(), nodoDestino.getParent().toString());
            ctrlProductos.cambiarOrigen(dtOrigen);
            ctrlProductos.cambiarDestino(dtDestino);
            JOptionPane.showMessageDialog(this, "Cambio realizado con exito", "Exito", JOptionPane.INFORMATION_MESSAGE);
            this.dispose();
            padre.setVisible(true);
        } else
            JOptionPane.showMessageDialog(this, "Por favor seleccione ciudades validas", "Seleccion invalida", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_botonConfirmarActionPerformed
    
    
    
    
    DefaultMutableTreeNode arbolCiudades;
    ICtrlProductos ctrlProductos;
    ModificacionServicio padre;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTree arbolCiudadesDestinoInterfaz;
    private javax.swing.JTree arbolCiudadesOrigenInterfaz;
    private javax.swing.JButton botonConfirmar;
    private javax.swing.JButton botonSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelDestino;
    private javax.swing.JLabel labelOrigen;
    // End of variables declaration//GEN-END:variables
}
