/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.tprog.estaciondetrabajo;

import com.tprog.logica.interfaces.ICtrlProductos;
import java.io.File;
import java.util.Set;
import java.util.Vector;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;

/**
 *
 * @author marccio
 */
public class ModificacionImagenes extends javax.swing.JInternalFrame {

    /**
     * Creates new form ReservasCliente
     * @param idCliente
     * @param padre
     */
    public ModificacionImagenes(ModificacionServicio padre, ICtrlProductos ctrlProductos) {
        this.padre = padre;
        this.ctrlProductos = ctrlProductos;
        initComponents();
        actualizarImagenes();
    }

    public void actualizarImagenes() {
        modelComboBox.clear();
        Set<String> imagenes = ctrlProductos.listarImagenes();
        for (String s : imagenes) {
            try {
                ImageIcon imagen = new ImageIcon(ModificacionImagenes.class.getResource(s));
                imagen.setDescription(s);
                modelComboBox.add(imagen);
                cantidadImagenes++;
            } catch (Exception e) {
                System.out.println(e.getMessage());
                break;
            }
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonSalir = new javax.swing.JButton();
        comboboxImagenes = new javax.swing.JComboBox(modelComboBox);
        botonQuitar = new javax.swing.JButton();
        botonAgregar = new javax.swing.JButton();

        setBorder(null);
        setPreferredSize(new java.awt.Dimension(690, 435));
        setVisible(true);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botonSalir.setText("Salir");
        botonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirActionPerformed(evt);
            }
        });
        getContentPane().add(botonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 200, -1, -1));

        comboboxImagenes.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(comboboxImagenes, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 280, 30));

        botonQuitar.setText("Quitar");
        botonQuitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonQuitarActionPerformed(evt);
            }
        });
        getContentPane().add(botonQuitar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 110, -1, -1));

        botonAgregar.setText("Agregar");
        botonAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgregarActionPerformed(evt);
            }
        });
        getContentPane().add(botonAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirActionPerformed
        this.dispose();
        padre.setVisible(true);
    }//GEN-LAST:event_botonSalirActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        /*
        descripcionInterfaz.setText(servicio.getDescripcion());
        precioInterfaz.setText(Float.toString(servicio.getPrecio()));
        */        
    }//GEN-LAST:event_formComponentShown

    private void botonQuitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonQuitarActionPerformed
        ImageIcon imagen = (ImageIcon) comboboxImagenes.getSelectedItem();
        if (imagen != null) {
            ctrlProductos.quitarImagen(imagen.getDescription());
            cantidadImagenes--;
            actualizarImagenes();
        }
    }//GEN-LAST:event_botonQuitarActionPerformed

    private void botonAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregarActionPerformed
        if (cantidadImagenes < 3) {
            JFileChooser chooser = new JFileChooser();
            chooser.showOpenDialog(null);
            File imagen = chooser.getSelectedFile();
            String nombreImagen = imagen.getAbsolutePath();
            ctrlProductos.agregarImagen(nombreImagen);
            actualizarImagenes();
        }
    }//GEN-LAST:event_botonAgregarActionPerformed

    
    Vector<Object> modelComboBox = new Vector<>();
    ICtrlProductos ctrlProductos;
    ModificacionServicio padre;
    int cantidadImagenes = 0;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAgregar;
    private javax.swing.JButton botonQuitar;
    private javax.swing.JButton botonSalir;
    private javax.swing.JComboBox comboboxImagenes;
    // End of variables declaration//GEN-END:variables
}
