/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.tprog.estaciondetrabajo;

import com.tprog.logica.dt.DTCliente;
import com.tprog.logica.dt.DTMinCliente;
import com.tprog.logica.dt.DTMinReserva;
import com.tprog.logica.interfaces.ICtrlReservas;
import com.tprog.logica.interfaces.ICtrlUsuarios;
import java.awt.Image;
import java.io.File;
import java.util.Set;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

public class RealizarReserva1 extends javax.swing.JInternalFrame {

    public RealizarReserva1(ICtrlUsuarios ctrlUsuarios, ICtrlReservas ctrlReservas) {
        initComponents();
        this.ctrlUsuarios = ctrlUsuarios;
        this.ctrlReservas = ctrlReservas;
        try {
            cargarDatos();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            this.dispose();
        }
    }

    void cargarDatos() throws Exception {
        //listaClientes
        try {
            Set<DTMinCliente> setClientes = ctrlUsuarios.listarClientes();
            if (!setClientes.isEmpty()) {
                listaClientes.removeAllElements();
                for (DTMinCliente dt : setClientes) {
                    listaClientes.add(dt.getNickname());
                }
                listaClientes.sort(null);
            } else {
                JOptionPane.showMessageDialog(this, "No hay clientes en el sistema.", "Error", JOptionPane.ERROR_MESSAGE);
            }
            this.updateUI();
        } catch (Exception e) {
            throw e;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        listaClientesInterfaz = new javax.swing.JComboBox(listaClientes);
        label = new javax.swing.JLabel();
        imagenUsuarioHolder = new javax.swing.JLabel();
        panelUsuario = new javax.swing.JScrollPane();
        detalleUsuario = new javax.swing.JTextArea();
        buttonSiguiente = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setClosable(true);
        setIconifiable(true);
        setTitle("Realizar Reserva");
        setPreferredSize(new java.awt.Dimension(640, 480));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        listaClientesInterfaz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listaClientesInterfazInterfazActionPerformed(evt);
            }
        });
        getContentPane().add(listaClientesInterfaz, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 290, -1));

        label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label.setText("Seleccione el Cliente que desea realizar la Reserva.");
        getContentPane().add(label, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, -1, -1));
        label.getAccessibleContext().setAccessibleDescription("");

        getContentPane().add(imagenUsuarioHolder, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 140, 140));

        detalleUsuario.setEditable(false);
        detalleUsuario.setColumns(20);
        detalleUsuario.setLineWrap(true);
        detalleUsuario.setRows(5);
        detalleUsuario.setWrapStyleWord(true);
        panelUsuario.setViewportView(detalleUsuario);

        getContentPane().add(panelUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 180, 230, 190));

        buttonSiguiente.setText("Siguiente >");
        buttonSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSiguienteActionPerformed(evt);
            }
        });
        getContentPane().add(buttonSiguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 400, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void listaClientesInterfazInterfazActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listaClientesInterfazInterfazActionPerformed
        //seleccionarCliente
        String cliente = (String) listaClientesInterfaz.getSelectedItem();
        if (cliente != null) {
            ctrlUsuarios.seleccionarCliente(cliente);
            try {
                DTCliente dt = ctrlUsuarios.infoCliente();
                detalleUsuario.setText(dt.toString());
                //cargar imagen
                String imagen = dt.getImagen();
                if (imagen != null) {
                    File f = new File(imagen);
                    Image img = ImageIO.read(f);
                    Image dimg = img.getScaledInstance(imagenUsuarioHolder.getWidth(), imagenUsuarioHolder.getHeight(), Image.SCALE_SMOOTH);
                    ImageIcon imageIcon = new ImageIcon(dimg);
                    imagenUsuarioHolder.setIcon(imageIcon);
                } else {
                    imagenUsuarioHolder.setIcon(null);
                }
                //obtener reservas
                reservas = dt.getReservas();
                //cargo la lista de reservas del usuario acá, y cuando se pidan las reservas se muestran
            } catch (Exception ex) {
                Logger.getLogger(RealizarReserva1.class.getName()).log(Level.SEVERE, null, ex);
                System.out.println(ex.getMessage());
            }

        }
    }//GEN-LAST:event_listaClientesInterfazInterfazActionPerformed

    private void buttonSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSiguienteActionPerformed
        String cliente = (String) listaClientesInterfaz.getSelectedItem();
        if (cliente != null) {
            ctrlReservas.liberarMemoriaControlador();
            ctrlReservas.seleccionarCliente(cliente);
            RealizarReserva2 rr2 = new RealizarReserva2(this, ctrlUsuarios, ctrlReservas);
            this.setVisible(false);
            getParent().add(rr2);
            rr2.setLocation(this.getLocation());
            rr2.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Seleccione un cliente por favor.", "Realizar Reserva", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_buttonSiguienteActionPerformed

    ICtrlReservas ctrlReservas;
    Set<DTMinReserva> reservas;
    ICtrlUsuarios ctrlUsuarios;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonSiguiente;
    private javax.swing.JTextArea detalleUsuario;
    private javax.swing.JLabel imagenUsuarioHolder;
    private javax.swing.JLabel label;
    private javax.swing.JComboBox listaClientesInterfaz;
    private Vector<String> listaClientes = new Vector<>();
    private javax.swing.JScrollPane panelUsuario;
    // End of variables declaration//GEN-END:variables
}
