/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.tprog.estaciondetrabajo;

import com.tprog.logica.dt.DTLineaReserva;
import com.tprog.logica.dt.DTReserva;
import com.tprog.logica.interfaces.ICtrlReservas;
import com.tprog.logica.interfaces.ICtrlUsuarios;
import java.util.HashMap;
import java.util.Iterator;
import java.util.Map;
import java.util.Set;
import java.util.Vector;
import javax.swing.JOptionPane;

public class RealizarReserva2 extends javax.swing.JInternalFrame {

	/**
	 * Creates new form RealizarReserva2
	 *
	 * @param padre
	 * @param ctrlUsuarios
	 * @param ctrlReservas
	 */
	public RealizarReserva2(RealizarReserva1 padre, ICtrlUsuarios ctrlUsuarios, ICtrlReservas ctrlReservas) {
		initComponents();
		this.padre = padre;
		this.ctrlReservas = ctrlReservas;
		jTextFieldPrecio.setEditable(false);
		cargarDatos();
	}

	void cargarDatos() {
		//limpio estructuras
		hashLineasReserva.clear();
		listaLineasReserva.clear();
		//pedir controlador
		DTReserva dtR = ctrlReservas.mostrarReservaTemporal();
		String precio = Float.toString(dtR.getPrecioTotal());
		jTextFieldPrecio.setText(precio);

		Set<DTLineaReserva> lineasReserva = dtR.getLineasReserva();
		Iterator it = lineasReserva.iterator();
		int i = 1;
		while (it.hasNext()) {
			hashLineasReserva.put(i, (DTLineaReserva) it.next());
			i++;
		}
		Iterator it2 = hashLineasReserva.entrySet().iterator();
		while (it2.hasNext()) {
			Map.Entry pair = (Map.Entry) it2.next();
			listaLineasReserva.add(Integer.toString((Integer) pair.getKey()));
		}

		//si ya elegí algún producto, pongo proveedorSeleccionado en true
		//para limitar los servicios y productos que se ofrecen después
		if (!ctrlReservas.mostrarReservaTemporal().getLineasReserva().isEmpty()) {
			proveedorSeleccionado = true;
		} else {
			proveedorSeleccionado = false;
		}
	}

	@Override
	public void dispose() {
		padre.dispose();
		super.dispose();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonAgregarServicio = new javax.swing.JButton();
        buttonAgregarPromocion = new javax.swing.JButton();
        buttonAtras = new javax.swing.JButton();
        buttonConfirmar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        listaServiciosInterfaz = new javax.swing.JComboBox(listaLineasReserva);
        jScrollPane3 = new javax.swing.JScrollPane();
        textAreaServicios = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldPrecio = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setClosable(true);
        setIconifiable(true);
        setTitle("Realizar Reserva");
        setPreferredSize(new java.awt.Dimension(640, 480));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonAgregarServicio.setText("Agregar Servicio");
        buttonAgregarServicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAgregarServicioActionPerformed(evt);
            }
        });
        getContentPane().add(buttonAgregarServicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 170, -1));

        buttonAgregarPromocion.setText("Agregar Promocion");
        buttonAgregarPromocion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAgregarPromocionActionPerformed(evt);
            }
        });
        getContentPane().add(buttonAgregarPromocion, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, 170, -1));

        buttonAtras.setText("< Atras");
        buttonAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAtrasActionPerformed(evt);
            }
        });
        getContentPane().add(buttonAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 400, -1, -1));

        buttonConfirmar.setText("Confirmar");
        buttonConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonConfirmarActionPerformed(evt);
            }
        });
        getContentPane().add(buttonConfirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 400, -1, -1));

        jLabel4.setText("Precio total:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, -1));

        jLabel5.setText("Servicios y Promociones");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 90, -1, -1));

        listaServiciosInterfaz.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        listaServiciosInterfaz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listaServiciosInterfazActionPerformed(evt);
            }
        });
        getContentPane().add(listaServiciosInterfaz, new org.netbeans.lib.awtextra.AbsoluteConstraints(341, 120, 220, -1));

        textAreaServicios.setColumns(20);
        textAreaServicios.setRows(5);
        jScrollPane3.setViewportView(textAreaServicios);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 160, 288, 220));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel7.setText("Datos actuales");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 140, 33));

        jTextFieldPrecio.setEditable(false);
        jTextFieldPrecio.setFocusable(false);
        getContentPane().add(jTextFieldPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 80, -1));

        jLabel1.setText("Aquí tiene la opción de agregar servicios y promociones a su reserva.");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 510, -1));

        jLabel2.setText("Para finalizar haga click en 'Confirmar'");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 410, 280, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonAgregarServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAgregarServicioActionPerformed
		RealizarReserva3 rr3 = new RealizarReserva3(this, ctrlReservas, proveedorSeleccionado);
		this.setVisible(false);
		getParent().add(rr3);
		rr3.setLocation(this.getLocation());
		rr3.setVisible(true);	
    }//GEN-LAST:event_buttonAgregarServicioActionPerformed

    private void buttonAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAtrasActionPerformed
		super.dispose();
		padre.setVisible(true);
    }//GEN-LAST:event_buttonAtrasActionPerformed

    private void buttonConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonConfirmarActionPerformed
		try {
			DTReserva dtr = ctrlReservas.mostrarReservaTemporal();
			ctrlReservas.seleccionarDTReserva(dtr);
			ctrlReservas.altaReserva();
			JOptionPane.showMessageDialog(this, "Reserva creada con éxito", "Realizar Reserva", JOptionPane.INFORMATION_MESSAGE);
			this.dispose();
		} catch (Exception ex) {
			JOptionPane.showMessageDialog(this, "Debe seleccionar al menos un servicio o promoción.", "Realizar Reserva", JOptionPane.INFORMATION_MESSAGE);
		}

    }//GEN-LAST:event_buttonConfirmarActionPerformed

    private void buttonAgregarPromocionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAgregarPromocionActionPerformed
		RealizarReserva4 rr4 = new RealizarReserva4(this, ctrlReservas, proveedorSeleccionado);
		this.setVisible(false);
		getParent().add(rr4);
		rr4.setLocation(this.getLocation());
		rr4.setVisible(true);
    }//GEN-LAST:event_buttonAgregarPromocionActionPerformed

    private void listaServiciosInterfazActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listaServiciosInterfazActionPerformed
		String servicio = (String) listaServiciosInterfaz.getSelectedItem();
		if (servicio != null) {
			int indice = Integer.parseInt(servicio);
			DTLineaReserva dt = (DTLineaReserva) hashLineasReserva.get(indice);
			textAreaServicios.setText(dt.toString());
			System.out.println(dt.toString());
		}
    }//GEN-LAST:event_listaServiciosInterfazActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
		cargarDatos();
		listaLineasReserva.sort(null);
		listaServiciosInterfaz.updateUI();
		textAreaServicios.setText("");
		this.updateUI();
    }//GEN-LAST:event_formComponentShown

	private final RealizarReserva1 padre;
	private final ICtrlReservas ctrlReservas;
	private Vector<String> listaLineasReserva = new Vector<>();
	private boolean proveedorSeleccionado = false;
	Map<Integer, DTLineaReserva> hashLineasReserva = new HashMap<>();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAgregarPromocion;
    private javax.swing.JButton buttonAgregarServicio;
    private javax.swing.JButton buttonAtras;
    private javax.swing.JButton buttonConfirmar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTextFieldPrecio;
    private javax.swing.JComboBox listaServiciosInterfaz;
    private javax.swing.JTextArea textAreaServicios;
    // End of variables declaration//GEN-END:variables

}
