/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.tprog.estaciondetrabajo;

import com.tprog.logica.dt.DTMinServicio;
import com.tprog.logica.interfaces.Fabrica;
import com.tprog.logica.interfaces.ICtrlProductos;
import com.tprog.logica.interfaces.ICtrlReservas;
import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;
import java.util.Set;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

public class RealizarReserva3 extends javax.swing.JInternalFrame {

    public RealizarReserva3(RealizarReserva2 padre, ICtrlReservas ctrlReservas, boolean proveedorSeleccionado) {

        //asignación de atributos
        this.padre = padre;
        this.ctrlReservas = ctrlReservas;
        f = Fabrica.getInstance();
        this.ctrlProductos = f.getICtrlProductos();
        initComponents();

		//obtengo los servicios a mostrar
        //si nunca elegí alguno, se muestran todos
        //si no, se muestran sólo los de ese proveedor
        Set<DTMinServicio> setServicios = this.ctrlReservas.listarServicios();
        Set<DTMinServicio> setServiciosP = null;
        if (!setServicios.isEmpty()) {
            if (proveedorSeleccionado) {
                //muestro solo los servicios del proveedor seleccionado
                setServiciosP = this.ctrlReservas.listarServiciosProveedor();
				//construyo un vector con la informacion a mostrar, porque
                //el comboBox solo funciona con Vector o List
                if (!setServiciosP.isEmpty()) {
                    for (DTMinServicio dt : setServiciosP) {
                        listaServicios.add(dt.getIdServicio());
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "No hay servicios en el sistema para el proveedor actual", "Error", JOptionPane.ERROR_MESSAGE);
                    this.dispose();
                }
            } else {
                for (DTMinServicio dt : setServicios) {
                    listaServicios.add(dt.getIdServicio());
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "No hay servicios en el sistema", "Error", JOptionPane.ERROR_MESSAGE);
            this.dispose();
        }
        listaServicios.sort(null);
    }

    private DefaultComboBoxModel<Integer> modelRange(int min, int max) {
        List<Integer> lista = new ArrayList<>();
        for (int i = min; i <= max; i++) {
            lista.add(i);
        }
        Integer[] anios = lista.toArray(new Integer[lista.size()]);
        return new DefaultComboBoxModel<Integer>(anios);
    }

		private boolean fechaValida(int dia, int mes, int anio) {
		switch (mes) {
			case 1:
			case 3:
			case 5:
			case 7:
			case 8:
			case 10:
			case 12:
				return dia < 32;
			case 4:
			case 6:
			case 9:
			case 11:
				return dia < 31;
			case 2: {
				if (((anio % 4 == 0) && (anio % 100 != 0)) || (anio % 400 == 0)) {
					//es año bisiesto
					return dia < 30;
				} else {
					return dia < 29;
				}
			}
			default:
				return false;
		}
	}
	
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        listaServiciosInterfaz = new javax.swing.JComboBox(listaServicios);
        panelUsuario = new javax.swing.JScrollPane();
        detalleServicio = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        buttonAtras = new javax.swing.JButton();
        buttonAgregar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        comboBoxDias1 = new com.tprog.estaciondetrabajo.customComponents.JComboBoxDias();
        comboBoxDias2 = new com.tprog.estaciondetrabajo.customComponents.JComboBoxDias();
        comboBoxMeses1 = new com.tprog.estaciondetrabajo.customComponents.JComboBoxMeses();
        comboBoxMeses2 = new com.tprog.estaciondetrabajo.customComponents.JComboBoxMeses();
        jTextFieldCantidad = new javax.swing.JTextField();
        comboBoxAnios1 = new javax.swing.JComboBox();
        comboBoxAnios2 = new javax.swing.JComboBox();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setClosable(true);
        setIconifiable(true);
        setTitle("Realizar Reserva - Agregar Servicio");
        setPreferredSize(new java.awt.Dimension(690, 435));
        setVisible(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        listaServiciosInterfaz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listaServiciosInterfazInterfazActionPerformed(evt);
            }
        });
        getContentPane().add(listaServiciosInterfaz, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 240, -1));

        detalleServicio.setEditable(false);
        detalleServicio.setColumns(20);
        detalleServicio.setLineWrap(true);
        detalleServicio.setRows(5);
        detalleServicio.setWrapStyleWord(true);
        panelUsuario.setViewportView(detalleServicio);

        getContentPane().add(panelUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 240, 128));

        jLabel1.setText("<html>Seleccione algun servicio del sistema para ver su información</html>");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, -1, -1));

        buttonAtras.setText("< Atras");
        buttonAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAtrasActionPerformed(evt);
            }
        });
        getContentPane().add(buttonAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 360, -1, -1));

        buttonAgregar.setText("Agregar");
        buttonAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAgregarActionPerformed(evt);
            }
        });
        getContentPane().add(buttonAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 360, -1, -1));

        jLabel2.setText("Cantidad");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 100, -1, -1));

        jLabel3.setText("Fecha de Inicio");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 150, -1, -1));

        jLabel4.setText("Fecha de Fin");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 150, -1, -1));

        jLabel5.setText("Día");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 190, -1, -1));

        jLabel6.setText("Mes");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 230, -1, -1));

        jLabel7.setText("Año");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 270, -1, -1));

        jLabel8.setText("Día");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 190, -1, -1));

        jLabel9.setText("Mes");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 230, -1, -1));

        jLabel10.setText("Año");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 270, -1, -1));
        getContentPane().add(comboBoxDias1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 190, 60, -1));
        getContentPane().add(comboBoxDias2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 190, 60, -1));
        getContentPane().add(comboBoxMeses1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 230, -1, -1));
        getContentPane().add(comboBoxMeses2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 230, -1, -1));
        getContentPane().add(jTextFieldCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 100, 70, -1));

        comboBoxAnios1.setModel(modeloAnios1);
        getContentPane().add(comboBoxAnios1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 270, 60, -1));

        comboBoxAnios2.setModel(modeloAnios2);
        getContentPane().add(comboBoxAnios2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 270, 60, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void listaServiciosInterfazInterfazActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listaServiciosInterfazInterfazActionPerformed
        String servicio = (String) listaServiciosInterfaz.getSelectedItem();
        if (servicio != null) {
            //buscar servicio
            DTMinServicio dt = null;
            servicios = ctrlReservas.listarServicios();
            Iterator it = servicios.iterator();
            boolean found = false;
            while (it.hasNext() && !found) {
                DTMinServicio tmp = (DTMinServicio) it.next();
                if (tmp.getIdServicio().equals(servicio)) {
                    dt = tmp;
                }
            }

            // Lo mando al Ctrl y muestro su DT
            ctrlProductos.seleccionarServicio(dt);
            detalleServicio.setVisible(true);
            detalleServicio.setText(ctrlProductos.infoServicio().toString());
        }
    }//GEN-LAST:event_listaServiciosInterfazInterfazActionPerformed

    private void buttonAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAtrasActionPerformed
        this.setVisible(false);
        this.padre.setVisible(true);
    }//GEN-LAST:event_buttonAtrasActionPerformed

    private void buttonAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAgregarActionPerformed
        String servicio = (String) listaServiciosInterfaz.getSelectedItem();
        if (servicio != null) {
            DTMinServicio dtmS = ctrlProductos.infoMinServicio();
            String proveedor = dtmS.getNicknameP();
            ctrlReservas.seleccionarProveedor(proveedor);
            ctrlReservas.seleccionarServicio(dtmS);
            ctrlProductos.seleccionarServicio(dtmS);

            //validar cantidad
            int cant = -1;
            String cantString = jTextFieldCantidad.getText();
            boolean okCant;
            try {
                cant = Integer.parseInt(cantString);
                okCant = cant > 0;
            } catch (NumberFormatException e) {
                okCant = false;
            }

            //fechas
            int diaI = (Integer) comboBoxDias1.getSelectedItem();
            int diaF = (Integer) comboBoxDias2.getSelectedItem();
            int mesI = comboBoxMeses1.getSelectedIndex();
            int mesF = comboBoxMeses2.getSelectedIndex();
            int anioI = (Integer) comboBoxAnios1.getSelectedItem();
            int anioF = (Integer) comboBoxAnios2.getSelectedItem();

            Date fechaInicio = new Date(anioI, mesI, diaI);
            Date fechaFinal = new Date(anioF, mesF, diaF);

            // Verifico las fechas
			boolean okFechaInicio = fechaValida(diaI, mesI + 1, anioI);
			boolean okFechaFinal = fechaValida(diaF, mesF + 1, anioF);
            boolean fechasCoherentes = fechaInicio.before(fechaFinal);
			boolean okFechas = okFechaInicio && okFechaFinal && fechasCoherentes;

            // Si todo esta ok
            if (okCant && okFechas) {
                // Envío la información al controlador
                ctrlReservas.ingresarLineaReserva(cant, fechaInicio, fechaFinal);

                JOptionPane.showMessageDialog(this, "El servicio fue agregado con éxito", "Éxito", JOptionPane.INFORMATION_MESSAGE);
                this.setVisible(false);
                this.padre.setVisible(true);
            } else { //hay algun dato erroneo
                String error = "";
                if (!okCant) {
                    error = "Por favor ingrese una cantidad válida.";
                } else if (!fechasCoherentes) {
                    error = "La fecha de inicio debe ser anterior a la fecha de finalización.";
                } else if (!okFechaInicio) {
					error = "La fecha de inicio ingresada no es correcta.";
				} else if (!okFechaFinal) {
					error = "La fecha de finalización ingresada no es correcta.";
				}
                JOptionPane.showMessageDialog(this, "Error! " + error, "Realizar Reserva", JOptionPane.INFORMATION_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un servicio.", "Realizar Reserva", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_buttonAgregarActionPerformed

    private ICtrlReservas ctrlReservas;
    private ICtrlProductos ctrlProductos;
    Fabrica f;
    Set<DTMinServicio> servicios;
    RealizarReserva2 padre;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAgregar;
    private javax.swing.JButton buttonAtras;
    private javax.swing.JComboBox comboBoxAnios1;
    private DefaultComboBoxModel<Integer> modeloAnios1 = modelRange(2015, 2099);
    private javax.swing.JComboBox comboBoxAnios2;
    private DefaultComboBoxModel<Integer> modeloAnios2 = modelRange(2015, 2099);
    private com.tprog.estaciondetrabajo.customComponents.JComboBoxDias comboBoxDias1;
    private com.tprog.estaciondetrabajo.customComponents.JComboBoxDias comboBoxDias2;
    private com.tprog.estaciondetrabajo.customComponents.JComboBoxMeses comboBoxMeses1;
    private com.tprog.estaciondetrabajo.customComponents.JComboBoxMeses comboBoxMeses2;
    private javax.swing.JTextArea detalleServicio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextFieldCantidad;
    private javax.swing.JComboBox listaServiciosInterfaz;
    private Vector<String> listaServicios = new Vector<>();
    private javax.swing.JScrollPane panelUsuario;
    // End of variables declaration//GEN-END:variables
}
