/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.tprog.estaciondetrabajo;

import com.tprog.logica.dt.DTMinPromocion;
import com.tprog.logica.interfaces.Fabrica;
import com.tprog.logica.interfaces.ICtrlProductos;
import com.tprog.logica.interfaces.ICtrlReservas;
import java.util.Date;
import java.util.Iterator;
import java.util.Set;
import java.util.Vector;
import javax.swing.JOptionPane;

public class RealizarReserva4 extends javax.swing.JInternalFrame {

	public RealizarReserva4(RealizarReserva2 padre, ICtrlReservas ctrlReservas, boolean proveedorSeleccionado) {
		
		//asignación de atributos
		this.padre = padre;
		this.ctrlReservas = ctrlReservas;
		f = Fabrica.getInstance();
		this.ctrlProductos = f.getICtrlProductos();
		initComponents();

		//obtengo los servicios a mostrar
		//si nunca elegí alguno, se muestran todos
		//si no, se muestran sólo los de ese proveedor
		Set<DTMinPromocion> setPromociones = this.ctrlReservas.listarPromociones();
		Set<DTMinPromocion> setPromocionesP = null;
		if (!setPromociones.isEmpty()) {
			if (proveedorSeleccionado) {
				//muestro solo los servicios del proveedor seleccionado
				setPromocionesP = this.ctrlReservas.listarPromocionesProveedor();
				//construyo un vector con la informacion a mostrar, porque
				//el comboBox solo funciona con Vector o List
				if (!setPromocionesP.isEmpty()) {
					for (DTMinPromocion dt : setPromocionesP) {
						listaPromociones.add(dt.getIdPromocion());
					}
				} else {
					JOptionPane.showMessageDialog(this, "No hay promociones en el sistema para el proveedor actual", "Error", JOptionPane.ERROR_MESSAGE);
					this.dispose();
				}
			} else {
				for (DTMinPromocion dt : setPromociones) {
					listaPromociones.add(dt.getIdPromocion());
				}
			}
		} else {
			JOptionPane.showMessageDialog(this, "No hay promociones en el sistema", "Error", JOptionPane.ERROR_MESSAGE);
			this.dispose();
		}
		listaPromociones.sort(null);
	}

	@Override
	public void dispose() {
		padre.dispose();
		super.dispose();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        listaPromocionesInterfaz = new javax.swing.JComboBox(listaPromociones);
        panelUsuario = new javax.swing.JScrollPane();
        detallePromocion = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        buttonAtras = new javax.swing.JButton();
        buttonAgregar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        comboBoxDias1 = new com.tprog.estaciondetrabajo.customComponents.JComboBoxDias();
        comboBoxDias2 = new com.tprog.estaciondetrabajo.customComponents.JComboBoxDias();
        comboBoxAnios1 = new com.tprog.estaciondetrabajo.customComponents.JComboBoxAnios(2015, 2099);
        comboBoxAnios2 = new com.tprog.estaciondetrabajo.customComponents.JComboBoxAnios(2015, 2099);
        comboBoxMeses1 = new com.tprog.estaciondetrabajo.customComponents.JComboBoxMeses();
        comboBoxMeses2 = new com.tprog.estaciondetrabajo.customComponents.JComboBoxMeses();
        jTextFieldCantidad = new javax.swing.JTextField();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setClosable(true);
        setIconifiable(true);
        setTitle("Realizar Reserva");
        setPreferredSize(new java.awt.Dimension(690, 435));
        setVisible(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        listaPromocionesInterfaz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listaPromocionesInterfazInterfazActionPerformed(evt);
            }
        });
        getContentPane().add(listaPromocionesInterfaz, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 240, -1));

        detallePromocion.setEditable(false);
        detallePromocion.setColumns(20);
        detallePromocion.setLineWrap(true);
        detallePromocion.setRows(5);
        detallePromocion.setWrapStyleWord(true);
        panelUsuario.setViewportView(detallePromocion);

        getContentPane().add(panelUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 240, 128));

        jLabel1.setText("<html>Seleccione alguna promoción del sistema para ver su información</html>");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, -1, -1));

        buttonAtras.setText("< Atras");
        buttonAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAtrasActionPerformed(evt);
            }
        });
        getContentPane().add(buttonAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 360, -1, -1));

        buttonAgregar.setText("Agregar");
        buttonAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAgregarActionPerformed(evt);
            }
        });
        getContentPane().add(buttonAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 360, -1, -1));

        jLabel2.setText("Cantidad");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 100, -1, -1));

        jLabel3.setText("Fecha de Inicio");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 150, -1, -1));

        jLabel4.setText("Fecha de Fin");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 150, -1, -1));

        jLabel5.setText("Día");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 190, -1, -1));

        jLabel6.setText("Mes");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 230, -1, -1));

        jLabel7.setText("Año");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 270, -1, -1));

        jLabel8.setText("Día");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 190, -1, -1));

        jLabel9.setText("Mes");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 230, -1, -1));

        jLabel10.setText("Año");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 270, -1, -1));
        getContentPane().add(comboBoxDias1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 190, 60, -1));
        getContentPane().add(comboBoxDias2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 190, 60, -1));
        getContentPane().add(comboBoxAnios1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 270, -1, -1));
        getContentPane().add(comboBoxAnios2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 270, -1, -1));
        getContentPane().add(comboBoxMeses1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 230, -1, -1));
        getContentPane().add(comboBoxMeses2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 230, -1, -1));
        getContentPane().add(jTextFieldCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 100, 70, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void listaPromocionesInterfazInterfazActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listaPromocionesInterfazInterfazActionPerformed
		String promocion = (String) listaPromocionesInterfaz.getSelectedItem();
		if (promocion != null) {
			//buscar promocion
			DTMinPromocion dt = null;
			promociones = ctrlReservas.listarPromociones();
			Iterator it = promociones.iterator();
			boolean found = false;
			while (it.hasNext() && !found) {
				DTMinPromocion tmp = (DTMinPromocion) it.next();
				if (tmp.getIdPromocion().equals(promocion)) {
					dt = tmp;
				}
			}

			// Lo mando al Ctrl y muestro su DT
			ctrlProductos.seleccionarPromocion(dt);
			detallePromocion.setVisible(true);
			detallePromocion.setText(ctrlProductos.infoPromocion().toString());
		}
    }//GEN-LAST:event_listaPromocionesInterfazInterfazActionPerformed

    private void buttonAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAtrasActionPerformed
		this.setVisible(false);
		this.padre.setVisible(true);
    }//GEN-LAST:event_buttonAtrasActionPerformed

    private void buttonAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAgregarActionPerformed
		String promocion = (String) listaPromocionesInterfaz.getSelectedItem();
		if (promocion != null) {
			DTMinPromocion dtmP = ctrlProductos.infoMinPromocion();
			String proveedor = dtmP.getNicknameP();
			ctrlReservas.seleccionarProveedor(proveedor);
			ctrlReservas.seleccionarPromocion(dtmP);
			ctrlProductos.seleccionarPromocion(dtmP);

			//validar cantidad
			int cant = -1;
			String cantString = jTextFieldCantidad.getText();
			boolean okCant;
			try {
				cant = Integer.parseInt(cantString);
				okCant = cant > 0;
			} catch (NumberFormatException e) {
				okCant = false;
			}

			//fechas
			int diaI = (Integer) comboBoxDias1.getSelectedItem();
			int diaF = (Integer) comboBoxDias2.getSelectedItem();
			int mesI = comboBoxMeses1.getSelectedIndex();
			int mesF = comboBoxMeses2.getSelectedIndex();
			int anioI = (Integer) comboBoxAnios1.getSelectedItem();
			int anioF = (Integer) comboBoxAnios2.getSelectedItem();

			Date fechaInicio = new Date(anioI, mesI, diaI);
			Date fechaFinal = new Date(anioF, mesF, diaF);
			Date fechaActual = new Date();
			
			// Verifico las fechas
			boolean fechasCoherentes = (fechaInicio.before(fechaFinal)) && (fechaInicio.after(fechaActual));

			// Si todo esta ok
			if (okCant && fechasCoherentes) {
				// Envío la información al controlador
				ctrlReservas.ingresarLineaReserva(cant, fechaInicio, fechaFinal);

				JOptionPane.showMessageDialog(this, "La promoción fue agregada con éxito", "Éxito", JOptionPane.INFORMATION_MESSAGE);
				this.setVisible(false);
				this.padre.setVisible(true);
			} else { //hay algun dato erroneo
				String error = "";
				if (!okCant) {
					error = "Por favor ingrese una cantidad válida.";
				} else if (!fechasCoherentes) {
					error = "La fecha de inicio debe ser posterior a la fecha actual.\n La fecha de fin debe ser postarior a la fecha de inicio.";
				}
				JOptionPane.showMessageDialog(this, "Error! " + error, "Realizar Reserva", JOptionPane.INFORMATION_MESSAGE);
			}
		} else {
			JOptionPane.showMessageDialog(this, "Debe seleccionar un servicio.", "Realizar Reserva", JOptionPane.INFORMATION_MESSAGE);
		}
    }//GEN-LAST:event_buttonAgregarActionPerformed

	private ICtrlReservas ctrlReservas;
	private ICtrlProductos ctrlProductos;
	Fabrica f;
	Set<DTMinPromocion> promociones;
	RealizarReserva2 padre;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAgregar;
    private javax.swing.JButton buttonAtras;
    private com.tprog.estaciondetrabajo.customComponents.JComboBoxAnios comboBoxAnios1;
    private com.tprog.estaciondetrabajo.customComponents.JComboBoxAnios comboBoxAnios2;
    private com.tprog.estaciondetrabajo.customComponents.JComboBoxDias comboBoxDias1;
    private com.tprog.estaciondetrabajo.customComponents.JComboBoxDias comboBoxDias2;
    private com.tprog.estaciondetrabajo.customComponents.JComboBoxMeses comboBoxMeses1;
    private com.tprog.estaciondetrabajo.customComponents.JComboBoxMeses comboBoxMeses2;
    private javax.swing.JTextArea detallePromocion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextFieldCantidad;
    private javax.swing.JComboBox listaPromocionesInterfaz;
    private Vector<String> listaPromociones = new Vector<>();
    private javax.swing.JScrollPane panelUsuario;
    // End of variables declaration//GEN-END:variables
}
