/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.tprog.estaciondetrabajo;

import com.tprog.logica.dt.DTMinProveedor;
import com.tprog.logica.dt.DTMinServicio;
import com.tprog.logica.dt.DTProveedor;
import com.tprog.logica.interfaces.Fabrica;
import com.tprog.logica.interfaces.ICtrlUsuarios;
import java.awt.BorderLayout;
import java.awt.Image;
import java.awt.event.MouseListener;
import java.io.File;
import java.util.Set;
import java.util.Vector;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.plaf.basic.BasicInternalFrameUI;

public class VerInformacionDeProveedor extends javax.swing.JInternalFrame {

	/**
	 * Creates new form VerInformacionDeCliente
	 *
	 */
	public VerInformacionDeProveedor() {
		initComponents();
		BasicInternalFrameUI basicInternalFrameUI = ((javax.swing.plaf.basic.BasicInternalFrameUI) this.getUI());
		for (MouseListener listener : basicInternalFrameUI.getNorthPane().getMouseListeners()) {
			basicInternalFrameUI.getNorthPane().removeMouseListener(listener);
		}
	}

	void cargarDatos() {
		//listaClientes
		Fabrica f = Fabrica.getInstance();
		ctrlUsuarios = f.getICtrlUsuarios();
		Set<DTMinProveedor> setProveedores = ctrlUsuarios.listarProveedores();
        //construyo un vector con la informacion a mostrar, porque
		//el comboBox solo funciona con Vector o List
		for (DTMinProveedor dt : setProveedores) {
			listaProveedores.add(dt.getNickname());
		}
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonSalir = new javax.swing.JButton();
        listaProveedoresInterfaz = new javax.swing.JComboBox(listaProveedores);
        label = new javax.swing.JLabel();
        imagenUsuario = new javax.swing.JLabel();
        panelUsuario = new javax.swing.JScrollPane();
        detalleUsuario = new javax.swing.JTextArea();
        botonServicios = new javax.swing.JButton();

        setBorder(null);
        setToolTipText("");
        setPreferredSize(new java.awt.Dimension(640, 480));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                formComponentHidden(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botonSalir.setText("Salir");
        botonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirActionPerformed(evt);
            }
        });
        getContentPane().add(botonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 400, -1, -1));

        listaProveedoresInterfaz.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                listaProveedoresInterfazInterfazComponentAdded(evt);
            }
        });
        listaProveedoresInterfaz.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                listaProveedoresInterfazItemStateChanged(evt);
            }
        });
        listaProveedoresInterfaz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listaProveedoresInterfazInterfazActionPerformed(evt);
            }
        });
        getContentPane().add(listaProveedoresInterfaz, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 270, -1));

        label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label.setText("Seleccione un proveedor del Sistema para ver su información");
        getContentPane().add(label, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 440, 30));
        label.getAccessibleContext().setAccessibleDescription("");

        imagenUsuario.setMaximumSize(new java.awt.Dimension(50, 50));
        imagenUsuario.setPreferredSize(new java.awt.Dimension(50, 50));
        getContentPane().add(imagenUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 140, 130));

        detalleUsuario.setEditable(false);
        detalleUsuario.setColumns(20);
        detalleUsuario.setLineWrap(true);
        detalleUsuario.setRows(5);
        detalleUsuario.setWrapStyleWord(true);
        panelUsuario.setViewportView(detalleUsuario);

        getContentPane().add(panelUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 180, 230, 190));

        botonServicios.setText("Ver servicios");
        botonServicios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonServiciosActionPerformed(evt);
            }
        });
        getContentPane().add(botonServicios, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 120, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
		cargarDatos();
    }//GEN-LAST:event_formComponentShown

    private void formComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentHidden
		listaProveedores.clear();
		servicios = null;
		imagenUsuario.setIcon(null);
		listaProveedoresInterfaz.setSelectedItem(null);
		detalleUsuario.setText("");
		detalleUsuario.setVisible(false);
    }//GEN-LAST:event_formComponentHidden

    private void listaProveedoresInterfazInterfazActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listaProveedoresInterfazInterfazActionPerformed
		//seleccionarProveedor
		String proveedor = (String) listaProveedoresInterfaz.getSelectedItem();
		if (proveedor != null) {
			ctrlUsuarios.seleccionarProveedor(proveedor);
			//muestro Text Area para la información del proveedor
			detalleUsuario.setVisible(true);
			DTProveedor dt = ctrlUsuarios.infoProveedor();
			detalleUsuario.setText(dt.toString());
			try {
				File f = new File(dt.getImagen());
				Image img = ImageIO.read(f);
				Image dimg = img.getScaledInstance(imagenUsuario.getWidth(), imagenUsuario.getHeight(), Image.SCALE_SMOOTH);
				ImageIcon imageIcon = new ImageIcon(dimg);
				imagenUsuario.setIcon(imageIcon);
			} catch (Exception e) {
				System.out.println("La imagen no pudo ser cargada");
			}
			//cargo la lista de servicios del proveedor
			servicios = ctrlUsuarios.listarServiciosProveedor();
		}
    }//GEN-LAST:event_listaProveedoresInterfazInterfazActionPerformed

    private void listaProveedoresInterfazInterfazComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_listaProveedoresInterfazInterfazComponentAdded

    }//GEN-LAST:event_listaProveedoresInterfazInterfazComponentAdded

    private void botonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirActionPerformed
		this.dispose();
    }//GEN-LAST:event_botonSalirActionPerformed

    private void listaProveedoresInterfazItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_listaProveedoresInterfazItemStateChanged
		// TODO add your handling code here:
    }//GEN-LAST:event_listaProveedoresInterfazItemStateChanged

    private void botonServiciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonServiciosActionPerformed
		String cliente = (String) listaProveedoresInterfaz.getSelectedItem();
		if (cliente != null) {
			ServiciosProveedor s = new ServiciosProveedor(this, servicios, ctrlUsuarios);
			this.setVisible(false);
			s.setVisible(true);
			getParent().add(s);
		}
    }//GEN-LAST:event_botonServiciosActionPerformed

	Set<DTMinServicio> servicios;
	ICtrlUsuarios ctrlUsuarios;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonSalir;
    private javax.swing.JButton botonServicios;
    private javax.swing.JTextArea detalleUsuario;
    private javax.swing.JLabel imagenUsuario;
    private javax.swing.JLabel label;
    private javax.swing.JComboBox listaProveedoresInterfaz;
    private Vector<String> listaProveedores = new Vector<>();
    private javax.swing.JScrollPane panelUsuario;
    // End of variables declaration//GEN-END:variables
}
