/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.tprog.estaciondetrabajo.customComponents;

import java.util.Iterator;
import java.util.List;
import java.util.Vector;

/**
 *
 * @author marccio
 */
public class SeleccionadorDosListas extends javax.swing.JPanel {

    /**
     * Creates new form seleccionadorDosListas
     */
    public SeleccionadorDosListas() {
        initComponents();
        //Esto es lo único que hay que modificar; para determinar los elementos
        //iniciales de las listas
        lista1.add("Chorolo1");
        lista1.add("Chorolo2");
        lista1.add("Chorolo3");
        lista1.add("Chorolo4");
        lista2.add("Chorolo7");
        lista2.add("Chorolo8");
        lista2.add("Chorolo9");
        lista2.add("Chorolo66");        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lista1Interfaz = new javax.swing.JList(lista1);
        jScrollPane2 = new javax.swing.JScrollPane();
        lista2Interfaz = new javax.swing.JList(lista2);
        addButton = new javax.swing.JButton();
        removeButton = new javax.swing.JButton();

        jScrollPane1.setViewportView(lista1Interfaz);

        jScrollPane2.setViewportView(lista2Interfaz);

        addButton.setText("->");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        removeButton.setText("<-");
        removeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(removeButton)
                    .addComponent(addButton, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(addButton)
                        .addGap(27, 27, 27)
                        .addComponent(removeButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2)
                            .addComponent(jScrollPane1))))
                .addContainerGap(66, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        List selected = lista1Interfaz.getSelectedValuesList();
        Iterator it1 = selected.iterator();
        while (it1.hasNext()){
            String actual = (String) it1.next();
            Iterator it2 = lista1.iterator();
            while (it2.hasNext()) {
                if (it2.next().equals(actual)) {
                    it2.remove();
                }
            }
            lista2.add(actual);
        }
        lista1Interfaz.updateUI();
        lista2Interfaz.updateUI();
    }//GEN-LAST:event_addButtonActionPerformed

    private void removeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeButtonActionPerformed
        List selected = lista2Interfaz.getSelectedValuesList();
        Iterator it1 = selected.iterator();
        while (it1.hasNext()){
            String actual = (String) it1.next();
            Iterator it2 = lista2.iterator();
            while (it2.hasNext()) {
                if (it2.next().equals(actual)) {
                    it2.remove();
                }
            }
            lista1.add(actual);
        }
        lista1Interfaz.updateUI();
        lista2Interfaz.updateUI();
    }//GEN-LAST:event_removeButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList lista1Interfaz;
    private Vector<String> lista1 = new Vector();
    private javax.swing.JList lista2Interfaz;
    private Vector<String> lista2 = new Vector();
    private javax.swing.JButton removeButton;
    // End of variables declaration//GEN-END:variables
}
