package tprog.estaciondetrabajo.ui;

import java.util.Set;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import javax.swing.tree.TreeSelectionModel;
import tprog.logica.dt.DTMinReserva;
import tprog.logica.dt.DTMinServicio;
import tprog.logica.interfaces.ICtrlProductos;

public class AltaDeServicio2 extends javax.swing.JInternalFrame {

	public AltaDeServicio2(AltaDeServicio1 padre, ICtrlProductos ctrlProductos, String proveedor) {
		initComponents();
		this.proveedor = proveedor;
		this.padre = padre;
		this.ctrlProductos = ctrlProductos;
		arbolCategorias.getSelectionModel().setSelectionMode(TreeSelectionModel.SINGLE_TREE_SELECTION);
		seleccionCategoriasInterfaz.getSelectionModel().setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
		getRootPane().setDefaultButton(botonSiguiente);
	}

	void cargarDatos() {
		DefaultMutableTreeNode raiz = ctrlProductos.listarCategorias();
		arbolCategorias.removeAll();
		arbolCategorias.setModel(new DefaultTreeModel(raiz));
		arbolCategorias.updateUI();
		seleccionCategorias.clear();
		seleccionCategoriasInterfaz.updateUI();
	}

	private boolean isWhiteSpace(String s) {
		return (s.matches("^\\s*$") || s.matches("^\\s.*"));
	}

	@Override
	public void dispose() {
		padre.dispose();
		super.dispose();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label = new javax.swing.JLabel();
        botonSiguiente = new javax.swing.JButton();
        buttonAtras = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        arbolCategorias = new javax.swing.JTree();
        botonAgregar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        seleccionCategoriasInterfaz = new javax.swing.JList(seleccionCategorias);
        botonQuitar = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        textPaneNombreServicio = new javax.swing.JTextPane();
        jLabel2 = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setClosable(true);
        setIconifiable(true);
        setTitle("Alta de Servicio - Categorías");
        setToolTipText("");
        setPreferredSize(new java.awt.Dimension(640, 480));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                formComponentHidden(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label.setText("Ingrese el nombre del nuevo Servicio y la categorías a las que pertenece.");
        getContentPane().add(label, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 486, 30));
        label.getAccessibleContext().setAccessibleDescription("");

        botonSiguiente.setText("Siguiente >");
        botonSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSiguienteActionPerformed(evt);
            }
        });
        getContentPane().add(botonSiguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 400, 120, -1));

        buttonAtras.setText("< Atras");
        buttonAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAtrasActionPerformed(evt);
            }
        });
        getContentPane().add(buttonAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 400, 120, -1));

        arbolCategorias.setModel(null);
        jScrollPane1.setViewportView(arbolCategorias);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 190, 270));

        botonAgregar.setText("<html><div align=\"center\">Agregar<br>Categoría</html>");
        botonAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgregarActionPerformed(evt);
            }
        });
        getContentPane().add(botonAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 190, 110, 40));

        jScrollPane2.setViewportView(seleccionCategoriasInterfaz);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 120, 170, 270));

        botonQuitar.setText("<html><div align=\"center\">Quitar<br>Categoría</html>");
        botonQuitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonQuitarActionPerformed(evt);
            }
        });
        getContentPane().add(botonQuitar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 290, 110, 40));

        jScrollPane3.setViewportView(textPaneNombreServicio);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, 199, -1));

        jLabel2.setText("Nombre del Servicio");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
		cargarDatos();
    }//GEN-LAST:event_formComponentShown

    private void formComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentHidden
		reservas = null;
    }//GEN-LAST:event_formComponentHidden

    private void buttonAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAtrasActionPerformed
		this.setVisible(false);
		this.padre.setVisible(true);
    }//GEN-LAST:event_buttonAtrasActionPerformed

    private void botonSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSiguienteActionPerformed
		String nombreServicio = textPaneNombreServicio.getText();
		String error = "";
		boolean valido = !isWhiteSpace(nombreServicio);
		boolean disponible = ((valido) && (ctrlProductos.idServicioDisponible(nombreServicio)));
		boolean okCategorias = !seleccionCategorias.isEmpty();
		
		if (disponible && okCategorias) {
			// Fijo el nombre
			DTMinServicio dtmServicio = new DTMinServicio(proveedor, nombreServicio);
			ctrlProductos.seleccionarServicio(dtmServicio);
			
			// Siguiente ventana
			AltaDeServicio3 as5 = new AltaDeServicio3(this, ctrlProductos);
			this.setVisible(false);
			getParent().add(as5);
			as5.setLocation(this.getLocation());
			as5.setVisible(true);			
		} else {
			if (!valido) {
				error = "El nombre de servicio ingresado no es válido.";
			} else if (!disponible) {
				error = "Ya existe un Servicio con ese nombre.";
			} else if (!okCategorias){
				error = "Por favor escoja al menos una categoría antes de avanzar.";
			}
			JOptionPane.showMessageDialog(this, error, "Alta de Servicio", JOptionPane.INFORMATION_MESSAGE);
		}
    }//GEN-LAST:event_botonSiguienteActionPerformed

    private void botonAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregarActionPerformed
		DefaultMutableTreeNode nodo = (DefaultMutableTreeNode) arbolCategorias.getLastSelectedPathComponent();
		if (nodo != null) {
			String categoriaActual = nodo.toString();
			//me fijo si la categoría ya no está en la selección actual
			if (!seleccionCategorias.contains(categoriaActual)) {
				//si la categoria seleccionada es simple, la agrego
				if (ctrlProductos.seleccionarCategoriaSimple(categoriaActual)) {
					seleccionCategorias.add(categoriaActual);
					if (seleccionCategorias.size() > 0) {
						botonQuitar.setEnabled(true);
					}
					seleccionCategorias.sort(null);
				} else {
					ctrlProductos.quitarCategoriaListada(categoriaActual);
					JOptionPane.showMessageDialog(this, "Por favor seleccione una categoria hoja", "Error", JOptionPane.ERROR_MESSAGE);
				}
			} else {
				JOptionPane.showMessageDialog(this, "Esa categoría ya fue agregada", "Error", JOptionPane.ERROR_MESSAGE);
			}
		} else {
			JOptionPane.showMessageDialog(this, "Por favor escoja una categoría antes de intentar agregar una.", "Error", JOptionPane.ERROR_MESSAGE);
		}
		seleccionCategoriasInterfaz.updateUI();
    }//GEN-LAST:event_botonAgregarActionPerformed

    private void botonQuitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonQuitarActionPerformed
		String categoria = (String) seleccionCategoriasInterfaz.getSelectedValue();
		if (categoria != null) {
			seleccionCategorias.remove(seleccionCategoriasInterfaz.getSelectedIndex());
			ctrlProductos.quitarCategoriaListada(categoria);
			seleccionCategorias.sort(null);
			if (seleccionCategorias.isEmpty()) {
				botonQuitar.setEnabled(false);
			}
			seleccionCategoriasInterfaz.clearSelection();
			seleccionCategoriasInterfaz.updateUI();
		} else {
			JOptionPane.showMessageDialog(this, "Tiene que seleccionar una categoría para intentar quitarla.", "Error", JOptionPane.ERROR_MESSAGE);
		}
    }//GEN-LAST:event_botonQuitarActionPerformed

	private AltaDeServicio1 padre;
	private String proveedor;
	Vector<String> seleccionCategorias = new Vector<>();
	Set<DTMinServicio> listaServicios;
	Set<DTMinReserva> reservas;
	ICtrlProductos ctrlProductos;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTree arbolCategorias;
    private javax.swing.JButton botonAgregar;
    private javax.swing.JButton botonQuitar;
    private javax.swing.JButton botonSiguiente;
    private javax.swing.JButton buttonAtras;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel label;
    private javax.swing.JList seleccionCategoriasInterfaz;
    private javax.swing.JTextPane textPaneNombreServicio;
    // End of variables declaration//GEN-END:variables
}
