package tprog.estaciondetrabajo.ui;

import java.awt.Image;
import java.io.File;
import java.util.Set;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import tprog.logica.dt.DTMinProveedor;
import tprog.logica.dt.DTMinServicio;
import tprog.logica.dt.DTProveedor;
import tprog.logica.interfaces.ICtrlProductos;
import tprog.logica.interfaces.ICtrlUsuarios;

public class AltaDeServicio1 extends javax.swing.JInternalFrame {

	public AltaDeServicio1(ICtrlUsuarios ctrlUsuarios, ICtrlProductos ctrlProductos) {
		this.ctrlProductos = ctrlProductos;
		this.ctrlUsuarios = ctrlUsuarios;
		initComponents();
		getRootPane().setDefaultButton(buttonSiguiente);
	}

	public void initCheck() {
		try {
			ctrlUsuarios.listarProveedores();
		} catch (Exception ex) {
			JOptionPane.showMessageDialog(this, ex.getMessage(), "Información", JOptionPane.INFORMATION_MESSAGE);
			this.dispose();
		}
	}

	private void refresh() {

		Set<DTMinProveedor> setProveedores;
		listaProveedores.clear();

		try {
			setProveedores = ctrlUsuarios.listarProveedores();
			if (!setProveedores.isEmpty()) {
				for (DTMinProveedor dt : setProveedores) {
					listaProveedores.add(dt.getNickname());
				}
				listaProveedores.sort(null);
			}
		} catch (Exception ex) {
			System.out.println("No hay proveedores que mostrar.");
		}
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        listaProveedoresInterfaz = new javax.swing.JComboBox(listaProveedores);
        label = new javax.swing.JLabel();
        imagenUsuarioHolder = new javax.swing.JLabel();
        panelUsuario = new javax.swing.JScrollPane();
        detalleUsuario = new javax.swing.JTextArea();
        buttonSiguiente = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setClosable(true);
        setIconifiable(true);
        setTitle("Alta de Servicio");
        setPreferredSize(new java.awt.Dimension(640, 480));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                formComponentHidden(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        listaProveedoresInterfaz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listaProveedoresInterfazInterfazActionPerformed(evt);
            }
        });
        getContentPane().add(listaProveedoresInterfaz, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 290, -1));

        label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label.setText("Seleccione el proveedor que va a dar de alta el Servicio.");
        getContentPane().add(label, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, -1, -1));
        label.getAccessibleContext().setAccessibleDescription("");

        getContentPane().add(imagenUsuarioHolder, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 140, 140));

        detalleUsuario.setEditable(false);
        detalleUsuario.setColumns(20);
        detalleUsuario.setLineWrap(true);
        detalleUsuario.setRows(5);
        detalleUsuario.setWrapStyleWord(true);
        panelUsuario.setViewportView(detalleUsuario);

        getContentPane().add(panelUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 180, 230, 190));

        buttonSiguiente.setText("Siguiente >");
        buttonSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSiguienteActionPerformed(evt);
            }
        });
        getContentPane().add(buttonSiguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 400, 120, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
		refresh();
    }//GEN-LAST:event_formComponentShown

    private void formComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentHidden
		servicios = null;
		imagenUsuarioHolder.setIcon(null);
		listaProveedoresInterfaz.setSelectedItem(null);
		detalleUsuario.setText("");
    }//GEN-LAST:event_formComponentHidden

    private void listaProveedoresInterfazInterfazActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listaProveedoresInterfazInterfazActionPerformed
		//seleccionarProveedor
		String proveedor = (String) listaProveedoresInterfaz.getSelectedItem();
		if (proveedor != null) {
			ctrlUsuarios.seleccionarProveedor(proveedor);
			//muestro Text Area para la información del proveedor
			detalleUsuario.setVisible(true);
			try {
				DTProveedor dt = ctrlUsuarios.infoProveedor();
				detalleUsuario.setText(dt.toString());
				String imagen = dt.getImagen();
				if (imagen != null) {
					File f = new File(dt.getImagen());
					Image img = ImageIO.read(f);
					Image dimg = img.getScaledInstance(imagenUsuarioHolder.getWidth(), imagenUsuarioHolder.getHeight(), Image.SCALE_SMOOTH);
					ImageIcon imageIcon = new ImageIcon(dimg);
					imagenUsuarioHolder.setIcon(imageIcon);
				} else {
					imagenUsuarioHolder.setIcon(null);
				}
			} catch (Exception ex) {
				Logger.getLogger(AltaDeServicio1.class.getName()).log(Level.SEVERE, null, ex);
				System.out.println("La imagen no pudo ser cargada");
				imagenUsuarioHolder.setIcon(null);
			}
		}
    }//GEN-LAST:event_listaProveedoresInterfazInterfazActionPerformed

    private void buttonSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSiguienteActionPerformed

		String proveedor = (String) listaProveedoresInterfaz.getSelectedItem();
		if (proveedor != null) {
			ctrlProductos.seleccionarProveedor(proveedor);
			AltaDeServicio2 as4 = new AltaDeServicio2(this, ctrlProductos, proveedor);
			this.setVisible(false);
			getParent().add(as4);
			as4.setLocation(this.getLocation());
			as4.setVisible(true);
		} else {
			JOptionPane.showMessageDialog(this, "Seleccione un proveedor.", "Alta de Servicio", JOptionPane.INFORMATION_MESSAGE);
		}
    }//GEN-LAST:event_buttonSiguienteActionPerformed

	Set<DTMinServicio> servicios;
	ICtrlProductos ctrlProductos;
	ICtrlUsuarios ctrlUsuarios;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonSiguiente;
    private javax.swing.JTextArea detalleUsuario;
    private javax.swing.JLabel imagenUsuarioHolder;
    private javax.swing.JLabel label;
    private javax.swing.JComboBox listaProveedoresInterfaz;
    private Vector<String> listaProveedores = new Vector<>();
    private javax.swing.JScrollPane panelUsuario;
    // End of variables declaration//GEN-END:variables
}
