/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tprog.estaciondetrabajo.ui;

import tprog.logica.dt.DTMinReserva;
import tprog.logica.dt.DTMinServicio;
import tprog.logica.interfaces.ICtrlProductos;
import java.util.Set;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import javax.swing.tree.TreeSelectionModel;

public class AltaDeServicio4 extends javax.swing.JInternalFrame {

    /**
     * Creates new form VerInformacionDeCliente
     *
     * @param padre
     * @param ctrlProductos
     */
    public AltaDeServicio4(AltaDeServicio3 padre, ICtrlProductos ctrlProductos) {
        initComponents();
        this.padre = padre;
        this.ctrlProductos = ctrlProductos;
        arbolCategorias.getSelectionModel().setSelectionMode(TreeSelectionModel.SINGLE_TREE_SELECTION);
        seleccionCategoriasInterfaz.getSelectionModel().setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
		getRootPane().setDefaultButton(botonSiguiente);
    }

    void cargarDatos() {
        DefaultMutableTreeNode raiz = ctrlProductos.listarCategorias();
        arbolCategorias.removeAll();
        arbolCategorias.setModel(new DefaultTreeModel(raiz));
        arbolCategorias.updateUI();
        seleccionCategorias.clear();
        seleccionCategoriasInterfaz.updateUI();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label = new javax.swing.JLabel();
        botonSiguiente = new javax.swing.JButton();
        buttonAtras = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        arbolCategorias = new javax.swing.JTree();
        botonAgregar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        seleccionCategoriasInterfaz = new javax.swing.JList(seleccionCategorias);
        botonQuitar = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setClosable(true);
        setIconifiable(true);
        setTitle("Alta de Servicio - Categorías");
        setToolTipText("");
        setPreferredSize(new java.awt.Dimension(640, 480));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                formComponentHidden(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label.setText("Seleccione la Categoría \"hoja\" a la que pertenece el nuevo Servicio.");
        getContentPane().add(label, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 486, 30));
        label.getAccessibleContext().setAccessibleDescription("");

        botonSiguiente.setText("Siguiente >");
        botonSiguiente.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                botonSiguienteComponentShown(evt);
            }
        });
        botonSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSiguienteActionPerformed(evt);
            }
        });
        getContentPane().add(botonSiguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 410, -1, -1));

        buttonAtras.setText("< Atras");
        buttonAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAtrasActionPerformed(evt);
            }
        });
        getContentPane().add(buttonAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 410, -1, -1));

        arbolCategorias.setModel(null);
        arbolCategorias.addTreeSelectionListener(new javax.swing.event.TreeSelectionListener() {
            public void valueChanged(javax.swing.event.TreeSelectionEvent evt) {
                arbolCategoriasValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(arbolCategorias);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 190, 280));

        botonAgregar.setText("<html><div align=\"center\">Agregar<br>Categoría</html>");
        botonAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgregarActionPerformed(evt);
            }
        });
        getContentPane().add(botonAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 160, 110, 50));

        jScrollPane2.setViewportView(seleccionCategoriasInterfaz);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 90, 170, 280));

        botonQuitar.setText("<html><div align=\"center\">Quitar<br>Categoría</html>");
        botonQuitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonQuitarActionPerformed(evt);
            }
        });
        getContentPane().add(botonQuitar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 260, 110, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        //pido de nuevo los datos en caso de que hayan cambiado
        cargarDatos();
    }//GEN-LAST:event_formComponentShown

    private void formComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentHidden
        reservas = null;
    }//GEN-LAST:event_formComponentHidden

    private void arbolCategoriasValueChanged(javax.swing.event.TreeSelectionEvent evt) {//GEN-FIRST:event_arbolCategoriasValueChanged
    }//GEN-LAST:event_arbolCategoriasValueChanged

    private void buttonAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAtrasActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        this.padre.setVisible(true);
    }//GEN-LAST:event_buttonAtrasActionPerformed

    private void botonSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSiguienteActionPerformed
        if (!seleccionCategorias.isEmpty()) {
            AltaDeServicio5 as5 = new AltaDeServicio5(this, ctrlProductos);
            this.setVisible(false);
            getParent().add(as5);
            as5.setLocation(this.getLocation());
            as5.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Por favor escoja al menos una categoría antes de avanzar.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_botonSiguienteActionPerformed

    @Override
    public void dispose() {
        padre.dispose();
        super.dispose();
    }

    private void botonAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregarActionPerformed
        DefaultMutableTreeNode nodo = (DefaultMutableTreeNode) arbolCategorias.getLastSelectedPathComponent();
        if (nodo != null) {
            String categoriaActual = nodo.toString();
            //me fijo si la categoría ya no está en la selección actual
            if (!seleccionCategorias.contains(categoriaActual)) {
                //si la categoria seleccionada es simple, la agrego
                if (ctrlProductos.seleccionarCategoriaSimple(categoriaActual)) {
                    seleccionCategorias.add(categoriaActual);
                    if (seleccionCategorias.size() > 0) {
                        botonQuitar.setEnabled(true);
                    }
                    seleccionCategorias.sort(null);
                } else {
                    ctrlProductos.quitarCategoriaListada(categoriaActual);
                    JOptionPane.showMessageDialog(this, "Por favor seleccione una categoria hoja", "Error", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(this, "Esa categoría ya fue agregada", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Por favor escoja una categoría antes de intentar agregar una.", "Error", JOptionPane.ERROR_MESSAGE);
        }
        seleccionCategoriasInterfaz.updateUI();
    }//GEN-LAST:event_botonAgregarActionPerformed

    private void botonQuitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonQuitarActionPerformed
        String categoria = (String) seleccionCategoriasInterfaz.getSelectedValue();
        if (categoria != null) {
            seleccionCategorias.remove(seleccionCategoriasInterfaz.getSelectedIndex());
            ctrlProductos.quitarCategoriaListada(categoria);
            seleccionCategorias.sort(null);
            if (seleccionCategorias.size() == 0) {
                botonQuitar.setEnabled(false);
            }
            seleccionCategoriasInterfaz.clearSelection();
            seleccionCategoriasInterfaz.updateUI();
        } else {
            JOptionPane.showMessageDialog(this, "Tiene que seleccionar una categoría para intentar quitarla.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_botonQuitarActionPerformed

    private void botonSiguienteComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_botonSiguienteComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_botonSiguienteComponentShown

    private AltaDeServicio3 padre;
    Vector<String> seleccionCategorias = new Vector<>();
    Set<DTMinServicio> listaServicios;
    Set<DTMinReserva> reservas;
    ICtrlProductos ctrlProductos;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTree arbolCategorias;
    private javax.swing.JButton botonAgregar;
    private javax.swing.JButton botonQuitar;
    private javax.swing.JButton botonSiguiente;
    private javax.swing.JButton buttonAtras;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel label;
    private javax.swing.JList seleccionCategoriasInterfaz;
    // End of variables declaration//GEN-END:variables
}
