package tprog.estaciondetrabajo.ui;

import javax.swing.JOptionPane;
import org.apache.commons.validator.routines.EmailValidator;
import tprog.logica.interfaces.ICtrlUsuarios;

public class AltaDeUsuario1 extends javax.swing.JInternalFrame {

	public AltaDeUsuario1(ICtrlUsuarios ctrlUsuarios) {
		this.ctrlUsuarios = ctrlUsuarios;
		initComponents();
		getRootPane().setDefaultButton(buttonSiguiente);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        buttonSiguiente = new javax.swing.JButton();
        jTextFieldNickname = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldEmail = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jPasswordField2 = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setClosable(true);
        setIconifiable(true);
        setTitle("Alta de Usuario");
        setPreferredSize(new java.awt.Dimension(640, 480));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Ingrese los datos del nuevo Usuario y haga click en \"Siguiente\" para continuar");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 560, -1));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("nickname");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, -1, -1));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("email");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, -1, -1));

        buttonSiguiente.setText("Siguiente >");
        buttonSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSiguienteActionPerformed(evt);
            }
        });
        getContentPane().add(buttonSiguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 400, 120, -1));
        getContentPane().add(jTextFieldNickname, new org.netbeans.lib.awtextra.AbsoluteConstraints(202, 110, 360, -1));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("contraseña");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 240, 180, -1));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("confirme su contraseña");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 290, 180, -1));
        getContentPane().add(jTextFieldEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(202, 170, 360, -1));

        jPasswordField1.setColumns(20);
        getContentPane().add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 240, 180, -1));

        jPasswordField2.setColumns(20);
        getContentPane().add(jPasswordField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 290, 180, -1));

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("Debe contener entre 4 y 20 carácteres.");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 330, 330, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

	private void buttonSiguienteActionPerformed(java.awt.event.ActionEvent evt) {
		String nickname = jTextFieldNickname.getText();
		String email = jTextFieldEmail.getText();
		char[] password1 = jPasswordField1.getPassword();
		char[] password2 = jPasswordField2.getPassword();
		String pass1 = new String(password1);
		String pass2 = new String(password2);
		System.out.println(pass1);
		System.out.println(pass2);

		//Verificacion de email
		EmailValidator emailValidator = EmailValidator.getInstance(true);
		boolean okEmail = emailValidator.isValid(email);

		//Verificacion de nickname
		boolean okEnblanco = !nickname.matches("^\\s*$");
		boolean okSinEspacios = !nickname.matches(".*(\\s+).*");
		boolean okNickname = okEnblanco && okSinEspacios;

		//Verificacion de contraseña
		boolean okPassword1 = pass1.length() >= 3 && pass1.length() <= 20;
		boolean okPassword2 = pass2.length() >= 3 && pass2.length() <= 20;
		boolean okPassword = (okPassword1 && okPassword2 && pass1.equals(pass2));

		boolean nicknameUnico = false;
		if (okNickname) {
			nicknameUnico = ctrlUsuarios.verificarNickname(nickname);
		}
		boolean emailUnico = false;
		if (okEmail) {
			emailUnico = ctrlUsuarios.verificarEmail(email);
		}

		if (okNickname && okEmail && !emailUnico && !nicknameUnico && okPassword) {
			AltaDeUsuario2 au2 = new AltaDeUsuario2(this, nickname, pass1, email, ctrlUsuarios);
			this.setVisible(false);
			getParent().add(au2);
			au2.setLocation(this.getLocation());
			au2.setVisible(true);
		} else {
			String error = "";
			if (!okNickname) {
				error = "Por favor ingrese un nickname válido.";
			} else if (!okEmail) {
				error = "Por favor ingrese un email válido.";
			} else if (nicknameUnico) {
				error = "Ya existe un usuario con el mismo nickname.";
			} else if (emailUnico) {
				error = "Ya existe un usuario con el mismo email.";
			} else if (!okPassword) {
				error = "Por favor verifique su contraseña.";
			}
			JOptionPane.showMessageDialog(this, "Error! " + error, "Alta de Usuario", JOptionPane.INFORMATION_MESSAGE);
		}
	}

	ICtrlUsuarios ctrlUsuarios;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonSiguiente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldNickname;
    // End of variables declaration//GEN-END:variables
}
