/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tprog.estaciondetrabajo.ui;

import java.awt.Component;
import java.util.ArrayList;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumn;
import tprog.logica.clases.Acceso;

public class RegistroDeAccesos extends javax.swing.JInternalFrame {
    
    /**
     * Creates new form RegristroAccesos
     */
    public RegistroDeAccesos(ArrayList<Acceso> listaAccesos){
        initComponents();
        cargarTablaBonita(listaAccesos);    
    }
    
    private void cargarTablaBonita(ArrayList<Acceso> listaAccesos){
        DefaultTableModel modelo = (DefaultTableModel) registro.getModel();
        //Centrar contenido de las celdas
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment( JLabel.CENTER );
        registro.setDefaultRenderer(String.class, centerRenderer);
        //CargarContenido
        String[] fila = new String[modelo.getColumnCount()];
        for (int i = 0; i < listaAccesos.size(); i++) {
            fila[0] = listaAccesos.get(i).getIdAcceso() +"";
            fila[1] = listaAccesos.get(i).getIPAddress();
            fila[2] = listaAccesos.get(i).getURLAddress();
            fila[3] = listaAccesos.get(i).getBrowser();
            fila[4] = listaAccesos.get(i).getSistemaOperativo(); 
            modelo.addRow(fila);
        }
        //ResizeColumnsWidth
        for (int column = 0; column < registro.getColumnCount(); column++) {
            TableColumn columna = registro.getColumnModel().getColumn(column);
            int preferredWidth = columna.getMinWidth();
            int maxWidth = 275;
            for (int row = 0; row < registro.getRowCount(); row++) {
                TableCellRenderer cellRenderer = registro.getCellRenderer(row, column);
                Component c = registro.prepareRenderer(cellRenderer, row, column);
                int width = c.getPreferredSize().width + registro.getIntercellSpacing().width;
                preferredWidth = Math.max(preferredWidth, width);
                if (preferredWidth >= maxWidth) {
                    preferredWidth = maxWidth;
                    break;
                }
            }
            columna.setPreferredWidth( preferredWidth );
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        registro = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setTitle("Registro de Accesos al Sitio Web");

        registro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "#Registro", "IP", "URL", "Browser", "Sist. Op."
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        registro.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(registro);
        if (registro.getColumnModel().getColumnCount() > 0) {
            registro.getColumnModel().getColumn(0).setResizable(false);
            registro.getColumnModel().getColumn(1).setResizable(false);
            registro.getColumnModel().getColumn(3).setResizable(false);
            registro.getColumnModel().getColumn(4).setResizable(false);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 624, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(162, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable registro;
    // End of variables declaration//GEN-END:variables
}
