package tprog.estaciondetrabajo.ui;

import java.awt.Image;
import java.io.File;
import java.util.Iterator;
import java.util.Map;
import java.util.Set;
import java.util.Vector;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import tprog.logica.dt.DTMinServicio;
import tprog.logica.dt.DTServicio;
import tprog.logica.interfaces.ICtrlProductos;

public class ServiciosPromocion extends javax.swing.JInternalFrame {

	public ServiciosPromocion(VerInformacionDePromocion padre, Map<DTMinServicio, Integer> servicios, ICtrlProductos ctrlProductos) {
		this.padre = padre;
		this.servicios = servicios;
		this.ctrlProductos = ctrlProductos;
		initComponents();
		//construyo lista para la interfaz usando el set
		for (Map.Entry<DTMinServicio, Integer> par : servicios.entrySet()) {
			listaServicios.add(par.getKey().getIdServicio());
		}
		comboboxImagenes.setEnabled(false);
		getRootPane().setDefaultButton(botonAtras);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        listaServiciosInterfaz = new javax.swing.JComboBox(listaServicios);
        panelUsuario = new javax.swing.JScrollPane();
        detalleServicio = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        botonAtras = new javax.swing.JButton();
        comboboxImagenes = new javax.swing.JComboBox(modelComboBox);
        jLabel2 = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setClosable(true);
        setIconifiable(true);
        setTitle("Ver Información de Promoción - Servicios");
        setPreferredSize(new java.awt.Dimension(640, 480));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        listaServiciosInterfaz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listaServiciosInterfazInterfazActionPerformed(evt);
            }
        });
        getContentPane().add(listaServiciosInterfaz, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 418, -1));

        detalleServicio.setEditable(false);
        detalleServicio.setColumns(20);
        detalleServicio.setLineWrap(true);
        detalleServicio.setRows(5);
        detalleServicio.setWrapStyleWord(true);
        panelUsuario.setViewportView(detalleServicio);

        getContentPane().add(panelUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 269, 230));

        jLabel1.setText("<html>Seleccione algun servicio de la promocion para ver su información</html>");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, -1, -1));

        botonAtras.setText("< Atras");
        botonAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAtrasActionPerformed(evt);
            }
        });
        getContentPane().add(botonAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 400, -1, -1));
        getContentPane().add(comboboxImagenes, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 160, 190, 130));

        jLabel2.setText("<html> Imágenes del servicio </html>");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 140, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void listaServiciosInterfazInterfazActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listaServiciosInterfazInterfazActionPerformed
		String servicio = (String) listaServiciosInterfaz.getSelectedItem();
		if (servicio != null) {

			// Busco el DTMinServicio para mandarlo al controlador
			DTMinServicio dt = null;
			Iterator<Map.Entry<DTMinServicio, Integer>> it = servicios.entrySet().iterator();
			boolean found = false;
			Integer cantidad = 0;
			while (it.hasNext() && !found) {
				Map.Entry<DTMinServicio, Integer> par = it.next();
				if (par.getKey().getIdServicio().equals(servicio)) {
					dt = par.getKey();
					found = true;
					cantidad = par.getValue();
				}
			}
			ctrlProductos.seleccionarServicio(dt);
			DTServicio dtServicio = ctrlProductos.infoServicio();

			
			detalleServicio.setVisible(true);
			String descripcion = dt.toString() + "Cantidad: " + Integer.toString(cantidad) + "\n";
			detalleServicio.setText(descripcion);
			
			//imagenes
			modelComboBox.clear();
			comboboxImagenes.setSelectedItem(null);
			Set<String> imagenes = dtServicio.getImagenes();
			for (String ruta : imagenes) {
				try {
					//obtengo archivo desde ruta
					File f = new File(ruta);
					//creo imagen
					Image img = ImageIO.read(f);
					//redimensiono para que entre en la JLabel
					int width = comboboxImagenes.getWidth();
					int height = img.getHeight(null) * width / img.getWidth(null);
					Image dimg = img.getScaledInstance(width, height, Image.SCALE_SMOOTH);
					//armo el ImageIcon
					ImageIcon imageIcon = new ImageIcon(dimg);
					imageIcon.setDescription(ruta);
					//lo asocio a la JLabel
					modelComboBox.add(imageIcon);
				} catch (Exception e) {
					System.out.println(e.getMessage());
					break;
				}
			}
			if (imagenes.size() > 0) {
				comboboxImagenes.setEnabled(true);
			} else {
				comboboxImagenes.setEnabled(false);
			}
			comboboxImagenes.updateUI();
		}
    }//GEN-LAST:event_listaServiciosInterfazInterfazActionPerformed

    private void botonAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAtrasActionPerformed
		this.dispose();
		padre.setVisible(true);
    }//GEN-LAST:event_botonAtrasActionPerformed

	Vector<ImageIcon> modelComboBox = new Vector<>();
	ICtrlProductos ctrlProductos;
	Map<DTMinServicio, Integer> servicios;
	VerInformacionDePromocion padre;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAtras;
    private javax.swing.JComboBox comboboxImagenes;
    private javax.swing.JTextArea detalleServicio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JComboBox listaServiciosInterfaz;
    private Vector<String> listaServicios = new Vector<>();
    private javax.swing.JScrollPane panelUsuario;
    // End of variables declaration//GEN-END:variables
}
