/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package estaciondetrabajo;

import java.awt.BorderLayout;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JInternalFrame;

/**
 *
 * @author marccio.silva
 */
public class VentanaPrincipal extends javax.swing.JFrame {
    /**

     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        //inicializo hash
        internalFrames = new HashMap<>();
        //inicializo internal frames
        verInformacionDeCliente = new VerInformacionDeCliente();
        verInformacionDePromocion = new VerInformacionDePromocion();
        verInformacionDeProveedor = new VerInformacionDeProveedor();
        verInformacionDeReserva = new VerInformacionDeReserva();
        verInformacionDeServicio = new VerInformacionDeServicio();
        cancelarReserva = new CancelarReserva();
        //las agrego al content pane
        getContentPane().add(verInformacionDeCliente, BorderLayout.CENTER);
        getContentPane().add(verInformacionDePromocion, BorderLayout.CENTER);
        getContentPane().add(verInformacionDeProveedor, BorderLayout.CENTER);
        getContentPane().add(verInformacionDeReserva, BorderLayout.CENTER);
        getContentPane().add(verInformacionDeServicio, BorderLayout.CENTER);
        getContentPane().add(cancelarReserva, BorderLayout.CENTER);
        //las agrego al hash
        internalFrames.put("verInformacionDeCliente", verInformacionDeCliente);
        internalFrames.put("verInformacionDePromocion", verInformacionDePromocion);
        internalFrames.put("verInformacionDeProveedor", verInformacionDeProveedor);
        internalFrames.put("verInformacionDeReserva", verInformacionDeReserva);
        internalFrames.put("verInformacionDeServicio", verInformacionDeServicio);
        internalFrames.put("cancelarReserva", cancelarReserva);
        //inicializacion autogenerada
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        menu = new javax.swing.JMenuBar();
        menuRegistros = new javax.swing.JMenu();
        menuItemAltaUsuario = new javax.swing.JMenuItem();
        menuItemAltaCategoria = new javax.swing.JMenuItem();
        menuItemAltaServicio = new javax.swing.JMenuItem();
        menuItemAltaPromocion = new javax.swing.JMenuItem();
        menuItemActualizarServicio = new javax.swing.JMenuItem();
        menuItemRealizarReserva = new javax.swing.JMenuItem();
        menuItemActualizarEstadoReserva = new javax.swing.JMenu();
        menuConsultas = new javax.swing.JMenu();
        menuItemVerInfoCliente = new javax.swing.JMenuItem();
        menuItemVerInfoProveedor = new javax.swing.JMenuItem();
        menuItemVerInfoServicio = new javax.swing.JMenuItem();
        menuItemVerInfoPromocion = new javax.swing.JMenuItem();
        menuItemVerInfoReserva = new javax.swing.JMenuItem();
        menuBorrados = new javax.swing.JMenu();
        menuItemCancelarReserva = new javax.swing.JMenuItem();

        jMenuItem6.setText("jMenuItem6");

        jMenuItem7.setText("jMenuItem7");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(640, 480));
        setMinimumSize(new java.awt.Dimension(640, 480));
        setPreferredSize(new java.awt.Dimension(640, 480));
        setResizable(false);

        menuRegistros.setText("Registros");

        menuItemAltaUsuario.setText("Alta de Usuario");
        menuItemAltaUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemAltaUsuarioActionPerformed(evt);
            }
        });
        menuRegistros.add(menuItemAltaUsuario);

        menuItemAltaCategoria.setText("Alta de Categoría");
        menuRegistros.add(menuItemAltaCategoria);

        menuItemAltaServicio.setText("Alta de Servicio");
        menuRegistros.add(menuItemAltaServicio);

        menuItemAltaPromocion.setText("Alta de Promoción");
        menuRegistros.add(menuItemAltaPromocion);

        menuItemActualizarServicio.setText("Actualizar Servicio");
        menuRegistros.add(menuItemActualizarServicio);

        menuItemRealizarReserva.setText("Realizar Reserva");
        menuRegistros.add(menuItemRealizarReserva);

        menuItemActualizarEstadoReserva.setText("Actualizar estado de Reserva");
        menuRegistros.add(menuItemActualizarEstadoReserva);

        menu.add(menuRegistros);

        menuConsultas.setText("Consultas");

        menuItemVerInfoCliente.setText("Ver Información de Cliente");
        menuItemVerInfoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemVerInfoClienteActionPerformed(evt);
            }
        });
        menuConsultas.add(menuItemVerInfoCliente);

        menuItemVerInfoProveedor.setText("Ver Información de Proveedor");
        menuItemVerInfoProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemVerInfoProveedorActionPerformed(evt);
            }
        });
        menuConsultas.add(menuItemVerInfoProveedor);

        menuItemVerInfoServicio.setText("Ver Información de Servicio");
        menuItemVerInfoServicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemVerInfoServicioActionPerformed(evt);
            }
        });
        menuConsultas.add(menuItemVerInfoServicio);

        menuItemVerInfoPromocion.setText("Ver Información de Promoción");
        menuItemVerInfoPromocion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemVerInfoPromocionActionPerformed(evt);
            }
        });
        menuConsultas.add(menuItemVerInfoPromocion);

        menuItemVerInfoReserva.setText("Ver Información de Reserva");
        menuItemVerInfoReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemVerInfoReservaActionPerformed(evt);
            }
        });
        menuConsultas.add(menuItemVerInfoReserva);

        menu.add(menuConsultas);

        menuBorrados.setText("Borrados");

        menuItemCancelarReserva.setText("Cancelar Reserva");
        menuItemCancelarReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemCancelarReservaActionPerformed(evt);
            }
        });
        menuBorrados.add(menuItemCancelarReserva);

        menu.add(menuBorrados);

        setJMenuBar(menu);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuItemAltaUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemAltaUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuItemAltaUsuarioActionPerformed
   
    private void menuItemVerInfoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemVerInfoClienteActionPerformed
        showInternalFrame("verInformacionDeCliente");
    }//GEN-LAST:event_menuItemVerInfoClienteActionPerformed

    private void menuItemVerInfoProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemVerInfoProveedorActionPerformed
        showInternalFrame("verInformacionDeProveedor");
    }//GEN-LAST:event_menuItemVerInfoProveedorActionPerformed

    private void menuItemVerInfoServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemVerInfoServicioActionPerformed
        showInternalFrame("verInformacionDeServicio");
    }//GEN-LAST:event_menuItemVerInfoServicioActionPerformed

    private void menuItemVerInfoPromocionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemVerInfoPromocionActionPerformed
    //verInformacionDePromocion
        showInternalFrame("verInformacionDePromocion");
    }//GEN-LAST:event_menuItemVerInfoPromocionActionPerformed

    private void menuItemVerInfoReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemVerInfoReservaActionPerformed
        showInternalFrame("verInformacionDeReserva");
    }//GEN-LAST:event_menuItemVerInfoReservaActionPerformed

    private void menuItemCancelarReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemCancelarReservaActionPerformed
        showInternalFrame("cancelarReserva");
    }//GEN-LAST:event_menuItemCancelarReservaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }
    
    //Operaciones auxiliares
    private void showInternalFrame(String id) {
        //muestra el internal frame identificado por id
        //solo funciona si el internal frame fue agregado al hash
        for (Map.Entry<String, JInternalFrame> internalFrame : internalFrames.entrySet()) {
            if (internalFrame.getKey() != id) {
                internalFrame.getValue().setVisible(false);
            } else internalFrame.getValue().setVisible(true);
        }
    }
    
    HashMap<String, JInternalFrame> internalFrames;
    //Variables nuestras
    private VerInformacionDeCliente verInformacionDeCliente;
    private VerInformacionDePromocion verInformacionDePromocion;
    private VerInformacionDeProveedor verInformacionDeProveedor;
    private VerInformacionDeReserva verInformacionDeReserva;
    private VerInformacionDeServicio verInformacionDeServicio;
    private CancelarReserva cancelarReserva;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuBar menu;
    private javax.swing.JMenu menuBorrados;
    private javax.swing.JMenu menuConsultas;
    private javax.swing.JMenu menuItemActualizarEstadoReserva;
    private javax.swing.JMenuItem menuItemActualizarServicio;
    private javax.swing.JMenuItem menuItemAltaCategoria;
    private javax.swing.JMenuItem menuItemAltaPromocion;
    private javax.swing.JMenuItem menuItemAltaServicio;
    private javax.swing.JMenuItem menuItemAltaUsuario;
    private javax.swing.JMenuItem menuItemCancelarReserva;
    private javax.swing.JMenuItem menuItemRealizarReserva;
    private javax.swing.JMenuItem menuItemVerInfoCliente;
    private javax.swing.JMenuItem menuItemVerInfoPromocion;
    private javax.swing.JMenuItem menuItemVerInfoProveedor;
    private javax.swing.JMenuItem menuItemVerInfoReserva;
    private javax.swing.JMenuItem menuItemVerInfoServicio;
    private javax.swing.JMenu menuRegistros;
    // End of variables declaration//GEN-END:variables
}
